//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstantsDLL.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenericResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConstantsDLL.Properties.GenericResources", typeof(GenericResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string aaaPROJECTaaa {
            get {
                return ResourceManager.GetString("aaaPROJECTaaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://api.github.com/repos/Kevin64/asset-information-and-registration/releases/latest.
        /// </summary>
        public static string AIR_API_URL {
            get {
                return ResourceManager.GetString("AIR_API_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 32.
        /// </summary>
        public static string ARCH32 {
            get {
                return ResourceManager.GetString("ARCH32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 64.
        /// </summary>
        public static string ARCH64 {
            get {
                return ResourceManager.GetString("ARCH64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Body.
        /// </summary>
        public static string BODY {
            get {
                return ResourceManager.GetString("BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a build.
        /// </summary>
        public static string BUILD {
            get {
                return ResourceManager.GetString("BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a config.json.
        /// </summary>
        public static string CONFIG_FILE {
            get {
                return ResourceManager.GetString("CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a true.
        /// </summary>
        public static string CONSOLE_OUT_CLI {
            get {
                return ResourceManager.GetString("CONSOLE_OUT_CLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a false.
        /// </summary>
        public static string CONSOLE_OUT_GUI {
            get {
                return ResourceManager.GetString("CONSOLE_OUT_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -.
        /// </summary>
        public static string DASH {
            get {
                return ResourceManager.GetString("DASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a dd/MM/yyyy.
        /// </summary>
        public static string DATE_DISPLAY {
            get {
                return ResourceManager.GetString("DATE_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a yyyy-MM-dd.
        /// </summary>
        public static string DATE_FORMAT {
            get {
                return ResourceManager.GetString("DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0.
        /// </summary>
        public static string DDR2_APCS {
            get {
                return ResourceManager.GetString("DDR2_APCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DDR2.
        /// </summary>
        public static string DDR2_NAME {
            get {
                return ResourceManager.GetString("DDR2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1.
        /// </summary>
        public static string DDR3_APCS {
            get {
                return ResourceManager.GetString("DDR3_APCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 24.
        /// </summary>
        public static string DDR3_MEMORY_TYPE_CODE {
            get {
                return ResourceManager.GetString("DDR3_MEMORY_TYPE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DDR3.
        /// </summary>
        public static string DDR3_NAME {
            get {
                return ResourceManager.GetString("DDR3_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 24.
        /// </summary>
        public static string DDR3_SMBIOS_CODE {
            get {
                return ResourceManager.GetString("DDR3_SMBIOS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 2.
        /// </summary>
        public static string DDR4_APCS_CODE {
            get {
                return ResourceManager.GetString("DDR4_APCS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DDR4.
        /// </summary>
        public static string DDR4_NAME {
            get {
                return ResourceManager.GetString("DDR4_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 26.
        /// </summary>
        public static string DDR4_SMBIOS_CODE {
            get {
                return ResourceManager.GetString("DDR4_SMBIOS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a alpha.
        /// </summary>
        public static string DEV_STATUS_ALPHA {
            get {
                return ResourceManager.GetString("DEV_STATUS_ALPHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a beta.
        /// </summary>
        public static string DEV_STATUS_BETA {
            get {
                return ResourceManager.GetString("DEV_STATUS_BETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RC.
        /// </summary>
        public static string DEV_STATUS_RC {
            get {
                return ResourceManager.GetString("DEV_STATUS_RC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DidItRunAlready.
        /// </summary>
        public static string DID_IT_RUN_ALREADY {
            get {
                return ResourceManager.GetString("DID_IT_RUN_ALREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a --.
        /// </summary>
        public static string DOUBLE_DASH {
            get {
                return ResourceManager.GetString("DOUBLE_DASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EB.
        /// </summary>
        public static string EB {
            get {
                return ResourceManager.GetString("EB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ETag.
        /// </summary>
        public static string ETAG {
            get {
                return ResourceManager.GetString("ETAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a False.
        /// </summary>
        public static string FALSE {
            get {
                return ResourceManager.GetString("FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FOP.
        /// </summary>
        public static string FOP {
            get {
                return ResourceManager.GetString("FOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://api.github.com/repos/Kevin64/features-overlay-presentation/releases/latest.
        /// </summary>
        public static string FOP_API_URL {
            get {
                return ResourceManager.GetString("FOP_API_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Software\\FOP.
        /// </summary>
        public static string FOP_REG_KEY {
            get {
                return ResourceManager.GetString("FOP_REG_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce.
        /// </summary>
        public static string FOP_RUN_ONCE_KEY {
            get {
                return ResourceManager.GetString("FOP_RUN_ONCE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &quot;C:\Program Files\FOP\FOP.lnk&quot;.
        /// </summary>
        public static string FOP_X64 {
            get {
                return ResourceManager.GetString("FOP_X64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &quot;C:\Program Files (x86)\FOP\FOP.lnk&quot;.
        /// </summary>
        public static string FOP_X86 {
            get {
                return ResourceManager.GetString("FOP_X86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -2.
        /// </summary>
        public static string FREE_CODE {
            get {
                return ResourceManager.GetString("FREE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MHz.
        /// </summary>
        public static string FREQUENCY {
            get {
                return ResourceManager.GetString("FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BIOS.
        /// </summary>
        public static string FW_TYPE_BIOS {
            get {
                return ResourceManager.GetString("FW_TYPE_BIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UEFI.
        /// </summary>
        public static string FW_TYPE_UEFI {
            get {
                return ResourceManager.GetString("FW_TYPE_UEFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GB.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GHz.
        /// </summary>
        public static string GHz {
            get {
                return ResourceManager.GetString("GHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Kevin64.
        /// </summary>
        public static string GITHUB_OWNER_AIR {
            get {
                return ResourceManager.GetString("GITHUB_OWNER_AIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Kevin64.
        /// </summary>
        public static string GITHUB_OWNER_FOP {
            get {
                return ResourceManager.GetString("GITHUB_OWNER_FOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a asset-information-and-registration.
        /// </summary>
        public static string GITHUB_REPO_AIR {
            get {
                return ResourceManager.GetString("GITHUB_REPO_AIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a features-overlay-presentation.
        /// </summary>
        public static string GITHUB_REPO_FOP {
            get {
                return ResourceManager.GetString("GITHUB_REPO_FOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HDD.
        /// </summary>
        public static string HDD {
            get {
                return ResourceManager.GetString("HDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 768.
        /// </summary>
        public static string HEIGHT {
            get {
                return ResourceManager.GetString("HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PC-.
        /// </summary>
        public static string HOSTNAME_PATTERN {
            get {
                return ResourceManager.GetString("HOSTNAME_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HtmlUrl.
        /// </summary>
        public static string HTML_URL {
            get {
                return ResourceManager.GetString("HTML_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a http://.
        /// </summary>
        public static string HTTP {
            get {
                return ResourceManager.GetString("HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a application/json.
        /// </summary>
        public static string HTTP_CONTENT_TYPE_JSON {
            get {
                return ResourceManager.GetString("HTTP_CONTENT_TYPE_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Software\\AssetInformationAndRegistration.
        /// </summary>
        public static string HWINFO_REG_PATH {
            get {
                return ResourceManager.GetString("HWINFO_REG_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_about_dark.png.
        /// </summary>
        public static string ICON_ABOUT_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_ABOUT_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_about_light.png.
        /// </summary>
        public static string ICON_ABOUT_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_ABOUT_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_agent_dark.png.
        /// </summary>
        public static string ICON_AGENT_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_AGENT_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_agent_light.png.
        /// </summary>
        public static string ICON_AGENT_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_AGENT_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ahci_dark.png.
        /// </summary>
        public static string ICON_AHCI_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_AHCI_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ahci_light.png.
        /// </summary>
        public static string ICON_AHCI_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_AHCI_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_asset_dark.png.
        /// </summary>
        public static string ICON_ASSET_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_ASSET_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_asset_light.png.
        /// </summary>
        public static string ICON_ASSET_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_ASSET_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_autotheme_dark.png.
        /// </summary>
        public static string ICON_AUTOTHEME_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_AUTOTHEME_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_autotheme_light.png.
        /// </summary>
        public static string ICON_AUTOTHEME_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_AUTOTHEME_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_bios_dark.png.
        /// </summary>
        public static string ICON_BIOS_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_BIOS_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_bios_light.png.
        /// </summary>
        public static string ICON_BIOS_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_BIOS_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_bios_version_dark.png.
        /// </summary>
        public static string ICON_BIOS_VERSION_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_BIOS_VERSION_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_bios_version_light.png.
        /// </summary>
        public static string ICON_BIOS_VERSION_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_BIOS_VERSION_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_brand_dark.png.
        /// </summary>
        public static string ICON_BRAND_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_BRAND_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_brand_light.png.
        /// </summary>
        public static string ICON_BRAND_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_BRAND_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_building_dark.png.
        /// </summary>
        public static string ICON_BUILDING_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_BUILDING_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_building_light.png.
        /// </summary>
        public static string ICON_BUILDING_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_BUILDING_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_cmos_battery_dark.png.
        /// </summary>
        public static string ICON_CMOS_BATTERY_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_CMOS_BATTERY_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_cmos_battery_light.png.
        /// </summary>
        public static string ICON_CMOS_BATTERY_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_CMOS_BATTERY_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_cpu_dark.png.
        /// </summary>
        public static string ICON_CPU_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_CPU_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_cpu_light.png.
        /// </summary>
        public static string ICON_CPU_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_CPU_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_darktheme_dark.png.
        /// </summary>
        public static string ICON_DARKTHEME_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_DARKTHEME_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_darktheme_light.png.
        /// </summary>
        public static string ICON_DARKTHEME_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_DARKTHEME_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_disk_size_dark.png.
        /// </summary>
        public static string ICON_DISK_SIZE_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_DISK_SIZE_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_disk_size_light.png.
        /// </summary>
        public static string ICON_DISK_SIZE_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_DISK_SIZE_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_gpu_dark.png.
        /// </summary>
        public static string ICON_GPU_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_GPU_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_gpu_light.png.
        /// </summary>
        public static string ICON_GPU_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_GPU_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_hdd_dark.png.
        /// </summary>
        public static string ICON_HDD_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_HDD_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_hdd_light.png.
        /// </summary>
        public static string ICON_HDD_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_HDD_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_hostname_dark.png.
        /// </summary>
        public static string ICON_HOSTNAME_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_HOSTNAME_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_hostname_light.png.
        /// </summary>
        public static string ICON_HOSTNAME_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_HOSTNAME_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_in_use_dark.png.
        /// </summary>
        public static string ICON_IN_USE_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_IN_USE_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_in_use_light.png.
        /// </summary>
        public static string ICON_IN_USE_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_IN_USE_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ip_dark.png.
        /// </summary>
        public static string ICON_IP_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_IP_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ip_light.png.
        /// </summary>
        public static string ICON_IP_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_IP_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_letter_dark.png.
        /// </summary>
        public static string ICON_LETTER_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_LETTER_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_letter_light.png.
        /// </summary>
        public static string ICON_LETTER_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_LETTER_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_lighttheme_dark.png.
        /// </summary>
        public static string ICON_LIGHTTHEME_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_LIGHTTHEME_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_lighttheme_light.png.
        /// </summary>
        public static string ICON_LIGHTTHEME_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_LIGHTTHEME_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_log_dark.png.
        /// </summary>
        public static string ICON_LOG_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_LOG_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_log_light.png.
        /// </summary>
        public static string ICON_LOG_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_LOG_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_mac_dark.png.
        /// </summary>
        public static string ICON_MAC_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_MAC_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_mac_light.png.
        /// </summary>
        public static string ICON_MAC_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_MAC_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_model_dark.png.
        /// </summary>
        public static string ICON_MODEL_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_MODEL_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_model_light.png.
        /// </summary>
        public static string ICON_MODEL_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_MODEL_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_password_dark.png.
        /// </summary>
        public static string ICON_PASSWORD_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_PASSWORD_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_password_light.png.
        /// </summary>
        public static string ICON_PASSWORD_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_PASSWORD_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_port_dark.png.
        /// </summary>
        public static string ICON_PORT_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_PORT_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_port_light.png.
        /// </summary>
        public static string ICON_PORT_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_PORT_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ram_dark.png.
        /// </summary>
        public static string ICON_RAM_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_RAM_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ram_light.png.
        /// </summary>
        public static string ICON_RAM_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_RAM_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_room_dark.png.
        /// </summary>
        public static string ICON_ROOM_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_ROOM_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_room_light.png.
        /// </summary>
        public static string ICON_ROOM_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_ROOM_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_seal_dark.png.
        /// </summary>
        public static string ICON_SEAL_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_SEAL_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_seal_light.png.
        /// </summary>
        public static string ICON_SEAL_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_SEAL_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_secure_boot_dark.png.
        /// </summary>
        public static string ICON_SECURE_BOOT_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_SECURE_BOOT_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_secure_boot_light.png.
        /// </summary>
        public static string ICON_SECURE_BOOT_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_SECURE_BOOT_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_serial_no_dark.png.
        /// </summary>
        public static string ICON_SERIAL_NUMBER_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_SERIAL_NUMBER_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_serial_no_light.png.
        /// </summary>
        public static string ICON_SERIAL_NUMBER_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_SERIAL_NUMBER_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_server_dark.png.
        /// </summary>
        public static string ICON_SERVER_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_SERVER_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_server_light.png.
        /// </summary>
        public static string ICON_SERVER_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_SERVER_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_service_dark.png.
        /// </summary>
        public static string ICON_SERVICE_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_SERVICE_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_service_light.png.
        /// </summary>
        public static string ICON_SERVICE_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_SERVICE_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_smart_dark.png.
        /// </summary>
        public static string ICON_SMART_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_SMART_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_smart_light.png.
        /// </summary>
        public static string ICON_SMART_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_SMART_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_standard_light.png.
        /// </summary>
        public static string ICON_STANDARD_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_STANDARD_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_standard_dark.png.
        /// </summary>
        public static string ICON_STARDARD_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_STARDARD_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_sticker_dark.png.
        /// </summary>
        public static string ICON_STICKER_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_STICKER_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_sticker_light.png.
        /// </summary>
        public static string ICON_STICKER_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_STICKER_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ticket_dark.png.
        /// </summary>
        public static string ICON_TICKET_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_TICKET_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ticket_light.png.
        /// </summary>
        public static string ICON_TICKET_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_TICKET_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_tpm_dark.png.
        /// </summary>
        public static string ICON_TPM_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_TPM_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_tpm_light.png.
        /// </summary>
        public static string ICON_TPM_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_TPM_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_type_dark.png.
        /// </summary>
        public static string ICON_TYPE_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_TYPE_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_type_light.png.
        /// </summary>
        public static string ICON_TYPE_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_TYPE_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_VT_x_dark.png.
        /// </summary>
        public static string ICON_VT_X_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_VT_X_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_VT_x_light.png.
        /// </summary>
        public static string ICON_VT_X_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_VT_X_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_who_dark.png.
        /// </summary>
        public static string ICON_WHO_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_WHO_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_who_light.png.
        /// </summary>
        public static string ICON_WHO_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_WHO_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_windows_dark.png.
        /// </summary>
        public static string ICON_WINDOWS_DARK_PATH {
            get {
                return ResourceManager.GetString("ICON_WINDOWS_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_windows_light.png.
        /// </summary>
        public static string ICON_WINDOWS_LIGHT_PATH {
            get {
                return ResourceManager.GetString("ICON_WINDOWS_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IDE.
        /// </summary>
        public static string IDE {
            get {
                return ResourceManager.GetString("IDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a \\img\\.
        /// </summary>
        public static string IMG_DIR {
            get {
                return ResourceManager.GetString("IMG_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .png.
        /// </summary>
        public static string IMG_EXT {
            get {
                return ResourceManager.GetString("IMG_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parameters.
        /// </summary>
        public static string INI_SECTION_1 {
            get {
                return ResourceManager.GetString("INI_SECTION_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a InstallDrivers.
        /// </summary>
        public static string INI_SECTION_1_1 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AddDrivers.
        /// </summary>
        public static string INI_SECTION_1_10 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ServerIP.
        /// </summary>
        public static string INI_SECTION_1_11 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ServerPort.
        /// </summary>
        public static string INI_SECTION_1_12 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Buildings.
        /// </summary>
        public static string INI_SECTION_1_13 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HWTypes.
        /// </summary>
        public static string INI_SECTION_1_14 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ThemeUI.
        /// </summary>
        public static string INI_SECTION_1_15 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logo1URL.
        /// </summary>
        public static string INI_SECTION_1_16 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logo2URL.
        /// </summary>
        public static string INI_SECTION_1_17 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logo3URL.
        /// </summary>
        public static string INI_SECTION_1_18 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CleanGarbage.
        /// </summary>
        public static string INI_SECTION_1_2 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ChangeResolution.
        /// </summary>
        public static string INI_SECTION_1_3 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ResolutionWidth.
        /// </summary>
        public static string INI_SECTION_1_4 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ResolutionHeight.
        /// </summary>
        public static string INI_SECTION_1_5 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DriverPath.
        /// </summary>
        public static string INI_SECTION_1_6 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RebootAfterFinished.
        /// </summary>
        public static string INI_SECTION_1_7 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PauseAfterFinished.
        /// </summary>
        public static string INI_SECTION_1_8 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LogLocation.
        /// </summary>
        public static string INI_SECTION_1_9 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enforcement.
        /// </summary>
        public static string INI_SECTION_2 {
            get {
                return ResourceManager.GetString("INI_SECTION_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RamLimitEnforcement.
        /// </summary>
        public static string INI_SECTION_2_1 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CheckForUpdates.
        /// </summary>
        public static string INI_SECTION_2_10 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SmartStatusEnforcement.
        /// </summary>
        public static string INI_SECTION_2_2 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MediaOperationModeEnforcement.
        /// </summary>
        public static string INI_SECTION_2_3 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HostnameEnforcement.
        /// </summary>
        public static string INI_SECTION_2_4 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FirmwareTypeEnforcement.
        /// </summary>
        public static string INI_SECTION_2_5 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FirmwareVersionEnforcement.
        /// </summary>
        public static string INI_SECTION_2_6 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SecureBootEnforcement.
        /// </summary>
        public static string INI_SECTION_2_7 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VirtualizationTechnologyEnforcement.
        /// </summary>
        public static string INI_SECTION_2_8 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TpmEnforcement.
        /// </summary>
        public static string INI_SECTION_2_9 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OrgData.
        /// </summary>
        public static string INI_SECTION_3 {
            get {
                return ResourceManager.GetString("INI_SECTION_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OrganizationFullName.
        /// </summary>
        public static string INI_SECTION_3_1 {
            get {
                return ResourceManager.GetString("INI_SECTION_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OrganizationAcronym.
        /// </summary>
        public static string INI_SECTION_3_2 {
            get {
                return ResourceManager.GetString("INI_SECTION_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DepartamentFullName.
        /// </summary>
        public static string INI_SECTION_3_3 {
            get {
                return ResourceManager.GetString("INI_SECTION_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DepartamentAcronym.
        /// </summary>
        public static string INI_SECTION_3_4 {
            get {
                return ResourceManager.GetString("INI_SECTION_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SubDepartamentFullName.
        /// </summary>
        public static string INI_SECTION_3_5 {
            get {
                return ResourceManager.GetString("INI_SECTION_3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SubDepartamentAcronym.
        /// </summary>
        public static string INI_SECTION_3_6 {
            get {
                return ResourceManager.GetString("INI_SECTION_3_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a output/.
        /// </summary>
        public static string JSON_SERVER_PATH {
            get {
                return ResourceManager.GetString("JSON_SERVER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a KB.
        /// </summary>
        public static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1.
        /// </summary>
        public static string LABEL_SCROLL_SPEED {
            get {
                return ResourceManager.GetString("LABEL_SCROLL_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LastInstallation.
        /// </summary>
        public static string LAST_INSTALL {
            get {
                return ResourceManager.GetString("LAST_INSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LastMaintenance.
        /// </summary>
        public static string LAST_MAINTENANCE {
            get {
                return ResourceManager.GetString("LAST_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limited.
        /// </summary>
        public static string LIMITED_USER_TYPE {
            get {
                return ResourceManager.GetString("LIMITED_USER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .log.
        /// </summary>
        public static string LOG_FILE_EXT {
            get {
                return ResourceManager.GetString("LOG_FILE_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AssetInformationAndRegistration.
        /// </summary>
        public static string LOG_FILENAME_AIR {
            get {
                return ResourceManager.GetString("LOG_FILENAME_AIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FOP.
        /// </summary>
        public static string LOG_FILENAME_FOP {
            get {
                return ResourceManager.GetString("LOG_FILENAME_FOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OfflineDriverInstallerOOBE.
        /// </summary>
        public static string LOG_FILENAME_OOBE {
            get {
                return ResourceManager.GetString("LOG_FILENAME_OOBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a XXXXXXXXXXXXXXX.
        /// </summary>
        public static string LOG_PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("LOG_PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ____________________________________________________________________________________________________.
        /// </summary>
        public static string LOG_SEPARATOR {
            get {
                return ResourceManager.GetString("LOG_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ------------------------------------------------.
        /// </summary>
        public static string LOG_SEPARATOR_SMALL {
            get {
                return ResourceManager.GetString("LOG_SEPARATOR_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HH:mm:ss.ffffff.
        /// </summary>
        public static string LOG_TIMESTAMP {
            get {
                return ResourceManager.GetString("LOG_TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\header\\login_banner_dark.png.
        /// </summary>
        public static string LOGIN_BANNER_DARK_PATH {
            get {
                return ResourceManager.GetString("LOGIN_BANNER_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\header\\login_banner_light.png.
        /// </summary>
        public static string LOGIN_BANNER_LIGHT_PATH {
            get {
                return ResourceManager.GetString("LOGIN_BANNER_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\header\\main_banner_dark.png.
        /// </summary>
        public static string MAIN_BANNER_DARK_PATH {
            get {
                return ResourceManager.GetString("MAIN_BANNER_DARK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\header\\main_banner_light.png.
        /// </summary>
        public static string MAIN_BANNER_LIGHT_PATH {
            get {
                return ResourceManager.GetString("MAIN_BANNER_LIGHT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 100.
        /// </summary>
        public static string MAX_SIZE {
            get {
                return ResourceManager.GetString("MAX_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MB.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AHCI.
        /// </summary>
        public static string MEDIA_OPERATION_AHCI {
            get {
                return ResourceManager.GetString("MEDIA_OPERATION_AHCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IDE/Legacy.
        /// </summary>
        public static string MEDIA_OPERATION_IDE {
            get {
                return ResourceManager.GetString("MEDIA_OPERATION_IDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NVMe.
        /// </summary>
        public static string MEDIA_OPERATION_NVME {
            get {
                return ResourceManager.GetString("MEDIA_OPERATION_NVME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MHz.
        /// </summary>
        public static string MHZ {
            get {
                return ResourceManager.GetString("MHZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 210.
        /// </summary>
        public static string NON_SECBOOT_GPU_1 {
            get {
                return ResourceManager.GetString("NON_SECBOOT_GPU_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 430.
        /// </summary>
        public static string NON_SECBOOT_GPU_2 {
            get {
                return ResourceManager.GetString("NON_SECBOOT_GPU_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -1.
        /// </summary>
        public static string NOT_AVAILABLE_CODE {
            get {
                return ResourceManager.GetString("NOT_AVAILABLE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a N/A.
        /// </summary>
        public static string NOT_AVAILABLE_NAME {
            get {
                return ResourceManager.GetString("NOT_AVAILABLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a offlineModeParameters.json.
        /// </summary>
        public static string OFFLINE_MODE_PARAMETER_FILE {
            get {
                return ResourceManager.GetString("OFFLINE_MODE_PARAMETER_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0.
        /// </summary>
        public static string OK_CODE {
            get {
                return ResourceManager.GetString("OK_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OK.
        /// </summary>
        public static string OK_NAME {
            get {
                return ResourceManager.GetString("OK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PB.
        /// </summary>
        public static string PB {
            get {
                return ResourceManager.GetString("PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PCI-E.
        /// </summary>
        public static string PCI_E {
            get {
                return ResourceManager.GetString("PCI_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1.
        /// </summary>
        public static string PRED_FAIL_CODE {
            get {
                return ResourceManager.GetString("PRED_FAIL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pred Fail.
        /// </summary>
        public static string PRED_FAIL_NAME {
            get {
                return ResourceManager.GetString("PRED_FAIL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AppLog.
        /// </summary>
        public static string PROGRAMDATA_FOLDERNAME {
            get {
                return ResourceManager.GetString("PROGRAMDATA_FOLDERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAID.
        /// </summary>
        public static string RAID {
            get {
                return ResourceManager.GetString("RAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a \\resources\\.
        /// </summary>
        public static string RESOURCES_DIR {
            get {
                return ResourceManager.GetString("RESOURCES_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8.
        /// </summary>
        public static string ROTATING_CIRCLE_INNER_RADIUS_100 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_INNER_RADIUS_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 10.
        /// </summary>
        public static string ROTATING_CIRCLE_INNER_RADIUS_125 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_INNER_RADIUS_125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 11.
        /// </summary>
        public static string ROTATING_CIRCLE_INNER_RADIUS_150 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_INNER_RADIUS_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 14.
        /// </summary>
        public static string ROTATING_CIRCLE_INNER_RADIUS_175 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_INNER_RADIUS_175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 15.
        /// </summary>
        public static string ROTATING_CIRCLE_INNER_RADIUS_200 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_INNER_RADIUS_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 17.
        /// </summary>
        public static string ROTATING_CIRCLE_INNER_RADIUS_225 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_INNER_RADIUS_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 17.
        /// </summary>
        public static string ROTATING_CIRCLE_INNER_RADIUS_250 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_INNER_RADIUS_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 22.
        /// </summary>
        public static string ROTATING_CIRCLE_INNER_RADIUS_300 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_INNER_RADIUS_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 24.
        /// </summary>
        public static string ROTATING_CIRCLE_INNER_RADIUS_350 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_INNER_RADIUS_350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 28.
        /// </summary>
        public static string ROTATING_CIRCLE_NUMBER_SPOKE_100 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_NUMBER_SPOKE_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 32.
        /// </summary>
        public static string ROTATING_CIRCLE_NUMBER_SPOKE_125 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_NUMBER_SPOKE_125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 36.
        /// </summary>
        public static string ROTATING_CIRCLE_NUMBER_SPOKE_150 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_NUMBER_SPOKE_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 40.
        /// </summary>
        public static string ROTATING_CIRCLE_NUMBER_SPOKE_175 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_NUMBER_SPOKE_175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 44.
        /// </summary>
        public static string ROTATING_CIRCLE_NUMBER_SPOKE_200 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_NUMBER_SPOKE_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 48.
        /// </summary>
        public static string ROTATING_CIRCLE_NUMBER_SPOKE_225 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_NUMBER_SPOKE_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 52.
        /// </summary>
        public static string ROTATING_CIRCLE_NUMBER_SPOKE_250 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_NUMBER_SPOKE_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 56.
        /// </summary>
        public static string ROTATING_CIRCLE_NUMBER_SPOKE_300 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_NUMBER_SPOKE_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 60.
        /// </summary>
        public static string ROTATING_CIRCLE_NUMBER_SPOKE_350 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_NUMBER_SPOKE_350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 9.
        /// </summary>
        public static string ROTATING_CIRCLE_OUTER_RADIUS_100 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_OUTER_RADIUS_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 12.
        /// </summary>
        public static string ROTATING_CIRCLE_OUTER_RADIUS_125 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_OUTER_RADIUS_125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 15.
        /// </summary>
        public static string ROTATING_CIRCLE_OUTER_RADIUS_150 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_OUTER_RADIUS_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 18.
        /// </summary>
        public static string ROTATING_CIRCLE_OUTER_RADIUS_175 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_OUTER_RADIUS_175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 22.
        /// </summary>
        public static string ROTATING_CIRCLE_OUTER_RADIUS_200 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_OUTER_RADIUS_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 24.
        /// </summary>
        public static string ROTATING_CIRCLE_OUTER_RADIUS_225 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_OUTER_RADIUS_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 24.
        /// </summary>
        public static string ROTATING_CIRCLE_OUTER_RADIUS_250 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_OUTER_RADIUS_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 32.
        /// </summary>
        public static string ROTATING_CIRCLE_OUTER_RADIUS_300 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_OUTER_RADIUS_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 35.
        /// </summary>
        public static string ROTATING_CIRCLE_OUTER_RADIUS_350 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_OUTER_RADIUS_350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1.
        /// </summary>
        public static string ROTATING_CIRCLE_ROTATION_SPEED {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_ROTATION_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 4.
        /// </summary>
        public static string ROTATING_CIRCLE_SPOKE_THICKNESS_100 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_SPOKE_THICKNESS_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string ROTATING_CIRCLE_SPOKE_THICKNESS_125 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_SPOKE_THICKNESS_125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string ROTATING_CIRCLE_SPOKE_THICKNESS_150 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_SPOKE_THICKNESS_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string ROTATING_CIRCLE_SPOKE_THICKNESS_175 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_SPOKE_THICKNESS_175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string ROTATING_CIRCLE_SPOKE_THICKNESS_200 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_SPOKE_THICKNESS_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string ROTATING_CIRCLE_SPOKE_THICKNESS_225 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_SPOKE_THICKNESS_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string ROTATING_CIRCLE_SPOKE_THICKNESS_250 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_SPOKE_THICKNESS_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string ROTATING_CIRCLE_SPOKE_THICKNESS_300 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_SPOKE_THICKNESS_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string ROTATING_CIRCLE_SPOKE_THICKNESS_350 {
            get {
                return ResourceManager.GetString("ROTATING_CIRCLE_SPOKE_THICKNESS_350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SATA.
        /// </summary>
        public static string SATA {
            get {
                return ResourceManager.GetString("SATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a shutdown.
        /// </summary>
        public static string SHUTDOWN_CMD_1 {
            get {
                return ResourceManager.GetString("SHUTDOWN_CMD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /r /f /t 0.
        /// </summary>
        public static string SHUTDOWN_CMD_2 {
            get {
                return ResourceManager.GetString("SHUTDOWN_CMD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SSD.
        /// </summary>
        public static string SSD {
            get {
                return ResourceManager.GetString("SSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /etc/config.json.
        /// </summary>
        public static string SUPPLY_CONFIG_DATA {
            get {
                return ResourceManager.GetString("SUPPLY_CONFIG_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SYSTEM ROM.
        /// </summary>
        public static string SYSTEM_ROM {
            get {
                return ResourceManager.GetString("SYSTEM_ROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TagName.
        /// </summary>
        public static string TAG_NAME {
            get {
                return ResourceManager.GetString("TAG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TB.
        /// </summary>
        public static string TB {
            get {
                return ResourceManager.GetString("TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AppsUseLightTheme.
        /// </summary>
        public static string THEME_REG_KEY {
            get {
                return ResourceManager.GetString("THEME_REG_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize.
        /// </summary>
        public static string THEME_REG_PATH {
            get {
                return ResourceManager.GetString("THEME_REG_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1000.
        /// </summary>
        public static string TIMER_INTERVAL {
            get {
                return ResourceManager.GetString("TIMER_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To Be Filled By O.E.M..
        /// </summary>
        public static string TO_BE_FILLED_BY_OEM {
            get {
                return ResourceManager.GetString("TO_BE_FILLED_BY_OEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a today.
        /// </summary>
        public static string TODAY {
            get {
                return ResourceManager.GetString("TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1.2.
        /// </summary>
        public static string TPM_1_2_NAME {
            get {
                return ResourceManager.GetString("TPM_1_2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 2.0.
        /// </summary>
        public static string TPM_2_0_NAME {
            get {
                return ResourceManager.GetString("TPM_2_0_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a True.
        /// </summary>
        public static string TRUE {
            get {
                return ResourceManager.GetString("TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0.
        /// </summary>
        public static string UNKNOWN_CODE {
            get {
                return ResourceManager.GetString("UNKNOWN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /api/v1/agent-username/.
        /// </summary>
        public static string V1_API_AGENT_URL {
            get {
                return ResourceManager.GetString("V1_API_AGENT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /api/v1/agent-id/.
        /// </summary>
        public static string V1_API_AGENTS_URL {
            get {
                return ResourceManager.GetString("V1_API_AGENTS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /api/v1/asset-hwuid/.
        /// </summary>
        public static string V1_API_ASSET_HWUID_URL {
            get {
                return ResourceManager.GetString("V1_API_ASSET_HWUID_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /api/v1/asset/.
        /// </summary>
        public static string V1_API_ASSET_URL {
            get {
                return ResourceManager.GetString("V1_API_ASSET_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /api/v1/model/.
        /// </summary>
        public static string V1_API_MODEL_URL {
            get {
                return ResourceManager.GetString("V1_API_MODEL_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /api/v1/parameters/.
        /// </summary>
        public static string V1_API_PARAMETERS_URL {
            get {
                return ResourceManager.GetString("V1_API_PARAMETERS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1366.
        /// </summary>
        public static string WIDTH {
            get {
                return ResourceManager.GetString("WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a \\windows10\\.
        /// </summary>
        public static string WIN_10_IMG_DIR {
            get {
                return ResourceManager.GetString("WIN_10_IMG_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 19041.
        /// </summary>
        public static string WIN_10_NT_BUILD {
            get {
                return ResourceManager.GetString("WIN_10_NT_BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 10.
        /// </summary>
        public static string WIN_10_NT_MAJOR {
            get {
                return ResourceManager.GetString("WIN_10_NT_MAJOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0.
        /// </summary>
        public static string WIN_10_NT_MINOR {
            get {
                return ResourceManager.GetString("WIN_10_NT_MINOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a \\windows11\\.
        /// </summary>
        public static string WIN_11_IMG_DIR {
            get {
                return ResourceManager.GetString("WIN_11_IMG_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 22621.
        /// </summary>
        public static string WIN_11_NT_BUILD {
            get {
                return ResourceManager.GetString("WIN_11_NT_BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 10.
        /// </summary>
        public static string WIN_11_NT_MAJOR {
            get {
                return ResourceManager.GetString("WIN_11_NT_MAJOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0.
        /// </summary>
        public static string WIN_11_NT_MINOR {
            get {
                return ResourceManager.GetString("WIN_11_NT_MINOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a \\windows7\\.
        /// </summary>
        public static string WIN_7_IMG_DIR {
            get {
                return ResourceManager.GetString("WIN_7_IMG_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7601.
        /// </summary>
        public static string WIN_7_NT_BUILD {
            get {
                return ResourceManager.GetString("WIN_7_NT_BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6.
        /// </summary>
        public static string WIN_7_NT_MAJOR {
            get {
                return ResourceManager.GetString("WIN_7_NT_MAJOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1.
        /// </summary>
        public static string WIN_7_NT_MINOR {
            get {
                return ResourceManager.GetString("WIN_7_NT_MINOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 10.
        /// </summary>
        public static string WINDOWS_10 {
            get {
                return ResourceManager.GetString("WINDOWS_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 11.
        /// </summary>
        public static string WINDOWS_11 {
            get {
                return ResourceManager.GetString("WINDOWS_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7.
        /// </summary>
        public static string WINDOWS_7 {
            get {
                return ResourceManager.GetString("WINDOWS_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8.
        /// </summary>
        public static string WINDOWS_8 {
            get {
                return ResourceManager.GetString("WINDOWS_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8.1.
        /// </summary>
        public static string WINDOWS_8_1 {
            get {
                return ResourceManager.GetString("WINDOWS_8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 17.
        /// </summary>
        public static string WMI_PCIE {
            get {
                return ResourceManager.GetString("WMI_PCIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 11.
        /// </summary>
        public static string WMI_SATA {
            get {
                return ResourceManager.GetString("WMI_SATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a x64.
        /// </summary>
        public static string X64 {
            get {
                return ResourceManager.GetString("X64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a x86.
        /// </summary>
        public static string X86 {
            get {
                return ResourceManager.GetString("X86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
