//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstantsDLL.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStrings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConstantsDLL.Properties.LogStrings", typeof(LogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string aaaPROJECTaaa {
            get {
                return ResourceManager.GetString("aaaPROJECTaaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Accessing APCS.
        /// </summary>
        public static string LOG_ACCESS_APCS {
            get {
                return ResourceManager.GetString("LOG_ACCESS_APCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Active Directory registered.
        /// </summary>
        public static string LOG_AD_REGISTERED {
            get {
                return ResourceManager.GetString("LOG_AD_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agent not present in database.
        /// </summary>
        public static string LOG_AGENT_NOT_EXIST {
            get {
                return ResourceManager.GetString("LOG_AGENT_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registering on the APCS Server.
        /// </summary>
        public static string LOG_APCS_REGISTERING {
            get {
                return ResourceManager.GetString("LOG_APCS_REGISTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Found dependency files.
        /// </summary>
        public static string LOG_APPFILE_FOUND {
            get {
                return ResourceManager.GetString("LOG_APPFILE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One or more missing dependency files.
        /// </summary>
        public static string LOG_APPFILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOG_APPFILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Asset not present in database.
        /// </summary>
        public static string LOG_ASSET_NOT_EXIST {
            get {
                return ResourceManager.GetString("LOG_ASSET_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authenticating user.
        /// </summary>
        public static string LOG_AUTH_USER {
            get {
                return ResourceManager.GetString("LOG_AUTH_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Automatically selecting theme.
        /// </summary>
        public static string LOG_AUTOTHEME_CHANGE {
            get {
                return ResourceManager.GetString("LOG_AUTOTHEME_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Checking for updates.
        /// </summary>
        public static string LOG_CHECKING_FOR_UPDATES {
            get {
                return ResourceManager.GetString("LOG_CHECKING_FOR_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arguments detected, starting in CLI mode. List of arguments.
        /// </summary>
        public static string LOG_CLI_MODE {
            get {
                return ResourceManager.GetString("LOG_CLI_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Closing About window.
        /// </summary>
        public static string LOG_CLOSING_ABOUTBOX {
            get {
                return ResourceManager.GetString("LOG_CLOSING_ABOUTBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ending program sequence.
        /// </summary>
        public static string LOG_CLOSING_CLI {
            get {
                return ResourceManager.GetString("LOG_CLOSING_CLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Finalizing login form.
        /// </summary>
        public static string LOG_CLOSING_LOGIN_FORM {
            get {
                return ResourceManager.GetString("LOG_CLOSING_LOGIN_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Finalizing main form.
        /// </summary>
        public static string LOG_CLOSING_MAIN_FORM {
            get {
                return ResourceManager.GetString("LOG_CLOSING_MAIN_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Closing processor form.
        /// </summary>
        public static string LOG_CLOSING_PROCESSOR_FORM {
            get {
                return ResourceManager.GetString("LOG_CLOSING_PROCESSOR_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Closing RAM form.
        /// </summary>
        public static string LOG_CLOSING_RAM_FORM {
            get {
                return ResourceManager.GetString("LOG_CLOSING_RAM_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Closing storage form.
        /// </summary>
        public static string LOG_CLOSING_STORAGE_FORM {
            get {
                return ResourceManager.GetString("LOG_CLOSING_STORAGE_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Closing updater window.
        /// </summary>
        public static string LOG_CLOSING_UPDATER_FORM {
            get {
                return ResourceManager.GetString("LOG_CLOSING_UPDATER_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Closing video card form.
        /// </summary>
        public static string LOG_CLOSING_VIDEO_CARD_FORM {
            get {
                return ResourceManager.GetString("LOG_CLOSING_VIDEO_CARD_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Connecting to GitHub.
        /// </summary>
        public static string LOG_CONNECTING_GITHUB {
            get {
                return ResourceManager.GetString("LOG_CONNECTING_GITHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Switching to dark theme.
        /// </summary>
        public static string LOG_DARK_THEME_CHANGE {
            get {
                return ResourceManager.GetString("LOG_DARK_THEME_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Running in DEBUG mode.
        /// </summary>
        public static string LOG_DEBUG_MODE {
            get {
                return ResourceManager.GetString("LOG_DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Completion of hardware collection.
        /// </summary>
        public static string LOG_END_COLLECTING {
            get {
                return ResourceManager.GetString("LOG_END_COLLECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Searching asset information.
        /// </summary>
        public static string LOG_FETCHING_ASSET_DATA {
            get {
                return ResourceManager.GetString("LOG_FETCHING_ASSET_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Searching available buildings and types of hardware in the local file.
        /// </summary>
        public static string LOG_FETCHING_LOCAL_DATA {
            get {
                return ResourceManager.GetString("LOG_FETCHING_LOCAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Searching hardware model information.
        /// </summary>
        public static string LOG_FETCHING_MODEL_DATA {
            get {
                return ResourceManager.GetString("LOG_FETCHING_MODEL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Searching available buildings and types of hardware.
        /// </summary>
        public static string LOG_FETCHING_SERVER_DATA {
            get {
                return ResourceManager.GetString("LOG_FETCHING_SERVER_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SATA/M.2 operating mode.
        /// </summary>
        public static string LOG_FIRMWARE_MEDIA_OPERATION_TYPE {
            get {
                return ResourceManager.GetString("LOG_FIRMWARE_MEDIA_OPERATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Secure Boot.
        /// </summary>
        public static string LOG_FIRMWARE_SECURE_BOOT {
            get {
                return ResourceManager.GetString("LOG_FIRMWARE_SECURE_BOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TPM version.
        /// </summary>
        public static string LOG_FIRMWARE_TPM {
            get {
                return ResourceManager.GetString("LOG_FIRMWARE_TPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Firmware type.
        /// </summary>
        public static string LOG_FIRMWARE_TYPE {
            get {
                return ResourceManager.GetString("LOG_FIRMWARE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Firmware version.
        /// </summary>
        public static string LOG_FIRMWARE_VERSION {
            get {
                return ResourceManager.GetString("LOG_FIRMWARE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Virtualization Technology.
        /// </summary>
        public static string LOG_FIRMWARE_VIRTUALIZATION_TECHNOLOGY {
            get {
                return ResourceManager.GetString("LOG_FIRMWARE_VIRTUALIZATION_TECHNOLOGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GitHub unreachable.
        /// </summary>
        public static string LOG_GITHUB_UNREACHABLE {
            get {
                return ResourceManager.GetString("LOG_GITHUB_UNREACHABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Missing arguments, starting in GUI mode.
        /// </summary>
        public static string LOG_GUI_MODE {
            get {
                return ResourceManager.GetString("LOG_GUI_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Brand.
        /// </summary>
        public static string LOG_HARDWARE_BRAND {
            get {
                return ResourceManager.GetString("LOG_HARDWARE_BRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Model.
        /// </summary>
        public static string LOG_HARDWARE_MODEL {
            get {
                return ResourceManager.GetString("LOG_HARDWARE_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Compliant configuration, ready for registration.
        /// </summary>
        public static string LOG_HARDWARE_PASSED {
            get {
                return ResourceManager.GetString("LOG_HARDWARE_PASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Serial Number.
        /// </summary>
        public static string LOG_HARDWARE_SERIAL_NUMBER {
            get {
                return ResourceManager.GetString("LOG_HARDWARE_SERIAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ------------------------ EXECUTION LOG ------------------------.
        /// </summary>
        public static string LOG_HEADER {
            get {
                return ResourceManager.GetString("LOG_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Start of execution.
        /// </summary>
        public static string LOG_INIT {
            get {
                return ResourceManager.GetString("LOG_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Starting registration process.
        /// </summary>
        public static string LOG_INIT_REGISTRY {
            get {
                return ResourceManager.GetString("LOG_INIT_REGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Switching to light theme.
        /// </summary>
        public static string LOG_LIGHT_THEME_CHANGE {
            get {
                return ResourceManager.GetString("LOG_LIGHT_THEME_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authentication failed.
        /// </summary>
        public static string LOG_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOG_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authentication performed successfully.
        /// </summary>
        public static string LOG_LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Model not present in database.
        /// </summary>
        public static string LOG_MODEL_NOT_EXIST {
            get {
                return ResourceManager.GetString("LOG_MODEL_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hostname.
        /// </summary>
        public static string LOG_NETWORK_HOSTNAME {
            get {
                return ResourceManager.GetString("LOG_NETWORK_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Primary IP Address.
        /// </summary>
        public static string LOG_NETWORK_IP_ADDRESS {
            get {
                return ResourceManager.GetString("LOG_NETWORK_IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Primary MAC Address.
        /// </summary>
        public static string LOG_NETWORK_MAC_ADDRESS {
            get {
                return ResourceManager.GetString("LOG_NETWORK_MAC_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No internet connection available.
        /// </summary>
        public static string LOG_NO_INTERNET_AVAILABLE {
            get {
                return ResourceManager.GetString("LOG_NO_INTERNET_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Offline execution mode.
        /// </summary>
        public static string LOG_OFFLINE_MODE {
            get {
                return ResourceManager.GetString("LOG_OFFLINE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Server is OFFLINE.
        /// </summary>
        public static string LOG_OFFLINE_SERVER {
            get {
                return ResourceManager.GetString("LOG_OFFLINE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Server is ONLINE.
        /// </summary>
        public static string LOG_ONLINE_SERVER {
            get {
                return ResourceManager.GetString("LOG_ONLINE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Opening About window.
        /// </summary>
        public static string LOG_OPENING_ABOUTBOX {
            get {
                return ResourceManager.GetString("LOG_OPENING_ABOUTBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Accessing release on GitHub.
        /// </summary>
        public static string LOG_OPENING_GITHUB {
            get {
                return ResourceManager.GetString("LOG_OPENING_GITHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Opening event log.
        /// </summary>
        public static string LOG_OPENING_LOG {
            get {
                return ResourceManager.GetString("LOG_OPENING_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Opening processor form.
        /// </summary>
        public static string LOG_OPENING_PROCESSOR_FORM {
            get {
                return ResourceManager.GetString("LOG_OPENING_PROCESSOR_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Opening RAM form.
        /// </summary>
        public static string LOG_OPENING_RAM_FORM {
            get {
                return ResourceManager.GetString("LOG_OPENING_RAM_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operning storage form.
        /// </summary>
        public static string LOG_OPENING_STORAGE_FORM {
            get {
                return ResourceManager.GetString("LOG_OPENING_STORAGE_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Opening video card form.
        /// </summary>
        public static string LOG_OPENING_VIDEO_CARD_FORM {
            get {
                return ResourceManager.GetString("LOG_OPENING_VIDEO_CARD_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operating system.
        /// </summary>
        public static string LOG_OPERATING_SYSTEM {
            get {
                return ResourceManager.GetString("LOG_OPERATING_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parameters file found.
        /// </summary>
        public static string LOG_PARAMETER_FILE_FOUND {
            get {
                return ResourceManager.GetString("LOG_PARAMETER_FILE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parameters file not found.
        /// </summary>
        public static string LOG_PARAMETER_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOG_PARAMETER_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Issues detected in the configuration.
        /// </summary>
        public static string LOG_PENDENCY_ERROR {
            get {
                return ResourceManager.GetString("LOG_PENDENCY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Checking server availability.
        /// </summary>
        public static string LOG_PINGGING_SERVER {
            get {
                return ResourceManager.GetString("LOG_PINGGING_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processor.
        /// </summary>
        public static string LOG_PROCESSOR {
            get {
                return ResourceManager.GetString("LOG_PROCESSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processor cache.
        /// </summary>
        public static string LOG_PROCESSOR_CACHE {
            get {
                return ResourceManager.GetString("LOG_PROCESSOR_CACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processor cores.
        /// </summary>
        public static string LOG_PROCESSOR_CORES {
            get {
                return ResourceManager.GetString("LOG_PROCESSOR_CORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processor frequency.
        /// </summary>
        public static string LOG_PROCESSOR_FREQUENCY {
            get {
                return ResourceManager.GetString("LOG_PROCESSOR_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processor ID.
        /// </summary>
        public static string LOG_PROCESSOR_ID {
            get {
                return ResourceManager.GetString("LOG_PROCESSOR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processor name.
        /// </summary>
        public static string LOG_PROCESSOR_NAME {
            get {
                return ResourceManager.GetString("LOG_PROCESSOR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processor threads.
        /// </summary>
        public static string LOG_PROCESSOR_THREADS {
            get {
                return ResourceManager.GetString("LOG_PROCESSOR_THREADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAM.
        /// </summary>
        public static string LOG_RAM {
            get {
                return ResourceManager.GetString("LOG_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAM module memory amount.
        /// </summary>
        public static string LOG_RAM_AMOUNT {
            get {
                return ResourceManager.GetString("LOG_RAM_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAM module frequency.
        /// </summary>
        public static string LOG_RAM_FREQUENCY {
            get {
                return ResourceManager.GetString("LOG_RAM_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAM module manufacturer.
        /// </summary>
        public static string LOG_RAM_MANUFACTURER {
            get {
                return ResourceManager.GetString("LOG_RAM_MANUFACTURER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAM module part number.
        /// </summary>
        public static string LOG_RAM_PART_NUMBER {
            get {
                return ResourceManager.GetString("LOG_RAM_PART_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAM module serial number.
        /// </summary>
        public static string LOG_RAM_SERIAL_NUMBER {
            get {
                return ResourceManager.GetString("LOG_RAM_SERIAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAM module slot.
        /// </summary>
        public static string LOG_RAM_SLOT {
            get {
                return ResourceManager.GetString("LOG_RAM_SLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAM module type.
        /// </summary>
        public static string LOG_RAM_TYPE {
            get {
                return ResourceManager.GetString("LOG_RAM_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration finished.
        /// </summary>
        public static string LOG_REGISTRY_FINISHED {
            get {
                return ResourceManager.GetString("LOG_REGISTRY_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Running in RELEASE mode.
        /// </summary>
        public static string LOG_RELEASE_MODE {
            get {
                return ResourceManager.GetString("LOG_RELEASE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One or more &apos;same&apos; arguments detected, however there is no existing record for the current asset. Computer must be registered first via GUI or via CLI with all command line options correctly filled in.
        /// </summary>
        public static string LOG_SAMEWORD_NOFIRSTREGISTRY {
            get {
                return ResourceManager.GetString("LOG_SAMEWORD_NOFIRSTREGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Server and port.
        /// </summary>
        public static string LOG_SERVER_DATA {
            get {
                return ResourceManager.GetString("LOG_SERVER_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Services made.
        /// </summary>
        public static string LOG_SERVICES_MADE {
            get {
                return ResourceManager.GetString("LOG_SERVICES_MADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Displaying list of commands.
        /// </summary>
        public static string LOG_SHOWING_HELP {
            get {
                return ResourceManager.GetString("LOG_SHOWING_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Initializing collection procedure thread.
        /// </summary>
        public static string LOG_START_COLLECT_THREAD {
            get {
                return ResourceManager.GetString("LOG_START_COLLECT_THREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Collecting asset data.
        /// </summary>
        public static string LOG_START_COLLECTING {
            get {
                return ResourceManager.GetString("LOG_START_COLLECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;ERROR&gt;.
        /// </summary>
        public static string LOG_STATUS_ERROR {
            get {
                return ResourceManager.GetString("LOG_STATUS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;INFORMATION&gt;.
        /// </summary>
        public static string LOG_STATUS_INFO {
            get {
                return ResourceManager.GetString("LOG_STATUS_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;MISCELLANEOUS&gt;.
        /// </summary>
        public static string LOG_STATUS_MISC {
            get {
                return ResourceManager.GetString("LOG_STATUS_MISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;WARNING&gt;.
        /// </summary>
        public static string LOG_STATUS_WARNING {
            get {
                return ResourceManager.GetString("LOG_STATUS_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Storage.
        /// </summary>
        public static string LOG_STORAGE {
            get {
                return ResourceManager.GetString("LOG_STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Storage device connection.
        /// </summary>
        public static string LOG_STORAGE_CONNECTION {
            get {
                return ResourceManager.GetString("LOG_STORAGE_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Storage device ID.
        /// </summary>
        public static string LOG_STORAGE_ID {
            get {
                return ResourceManager.GetString("LOG_STORAGE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Storage device model.
        /// </summary>
        public static string LOG_STORAGE_MODEL {
            get {
                return ResourceManager.GetString("LOG_STORAGE_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Storage device serial number.
        /// </summary>
        public static string LOG_STORAGE_SERIAL_NUMBER {
            get {
                return ResourceManager.GetString("LOG_STORAGE_SERIAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Storage device size.
        /// </summary>
        public static string LOG_STORAGE_SIZE {
            get {
                return ResourceManager.GetString("LOG_STORAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Storage device S.M.A.R.T. status.
        /// </summary>
        public static string LOG_STORAGE_SMART_STATUS {
            get {
                return ResourceManager.GetString("LOG_STORAGE_SMART_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Storage device type.
        /// </summary>
        public static string LOG_STORAGE_TYPE {
            get {
                return ResourceManager.GetString("LOG_STORAGE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Active theme.
        /// </summary>
        public static string LOG_THEME {
            get {
                return ResourceManager.GetString("LOG_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dark.
        /// </summary>
        public static string LOG_THEME_DARK {
            get {
                return ResourceManager.GetString("LOG_THEME_DARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Light.
        /// </summary>
        public static string LOG_THEME_LIGHT {
            get {
                return ResourceManager.GetString("LOG_THEME_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to check for updates.
        /// </summary>
        public static string LOG_UPDATE_CHECK_IMPOSSIBLE {
            get {
                return ResourceManager.GetString("LOG_UPDATE_CHECK_IMPOSSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Video card.
        /// </summary>
        public static string LOG_VIDEO_CARD {
            get {
                return ResourceManager.GetString("LOG_VIDEO_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Video card ID.
        /// </summary>
        public static string LOG_VIDEO_CARD_ID {
            get {
                return ResourceManager.GetString("LOG_VIDEO_CARD_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Video card name.
        /// </summary>
        public static string LOG_VIDEO_CARD_NAME {
            get {
                return ResourceManager.GetString("LOG_VIDEO_CARD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Video card memory.
        /// </summary>
        public static string LOG_VIDEO_CARD_RAM {
            get {
                return ResourceManager.GetString("LOG_VIDEO_CARD_RAM", resourceCulture);
            }
        }
    }
}
