//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstantsDLL.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConstantsDLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string AAAString1 {
            get {
                return ResourceManager.GetString("AAAString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AHCI.
        /// </summary>
        public static string ahci {
            get {
                return ResourceManager.GetString("ahci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 32.
        /// </summary>
        public static string arch32 {
            get {
                return ResourceManager.GetString("arch32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 64.
        /// </summary>
        public static string arch64 {
            get {
                return ResourceManager.GetString("arch64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BIOS.
        /// </summary>
        public static string bios {
            get {
                return ResourceManager.GetString("bios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a System.IO.Path.GetTempPath() + Resources.fileBios.
        /// </summary>
        public static string biosPath {
            get {
                return ResourceManager.GetString("biosPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a build.
        /// </summary>
        public static string build {
            get {
                return ResourceManager.GetString("build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a System.IO.Path.GetTempPath() + Resources.fileConfig.
        /// </summary>
        public static string configPath {
            get {
                return ResourceManager.GetString("configPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a true.
        /// </summary>
        public static string consoleOutCLI {
            get {
                return ResourceManager.GetString("consoleOutCLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a false.
        /// </summary>
        public static string consoleOutGUI {
            get {
                return ResourceManager.GetString("consoleOutGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -.
        /// </summary>
        public static string DASH {
            get {
                return ResourceManager.GetString("DASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DDR2.
        /// </summary>
        public static string ddr2 {
            get {
                return ResourceManager.GetString("ddr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DDR3.
        /// </summary>
        public static string ddr3 {
            get {
                return ResourceManager.GetString("ddr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 24.
        /// </summary>
        public static string ddr3memorytype {
            get {
                return ResourceManager.GetString("ddr3memorytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 24.
        /// </summary>
        public static string ddr3smbios {
            get {
                return ResourceManager.GetString("ddr3smbios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DDR4.
        /// </summary>
        public static string ddr4 {
            get {
                return ResourceManager.GetString("ddr4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 26.
        /// </summary>
        public static string ddr4smbios {
            get {
                return ResourceManager.GetString("ddr4smbios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a definitions.ini.
        /// </summary>
        public static string defFile {
            get {
                return ResourceManager.GetString("defFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DidItRunAlready.
        /// </summary>
        public static string DidItRunAlready {
            get {
                return ResourceManager.GetString("DidItRunAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a bios.json.
        /// </summary>
        public static string fileBios {
            get {
                return ResourceManager.GetString("fileBios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a config.json.
        /// </summary>
        public static string fileConfig {
            get {
                return ResourceManager.GetString("fileConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /etc/.
        /// </summary>
        public static string fileConfigPath {
            get {
                return ResourceManager.GetString("fileConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a login.json.
        /// </summary>
        public static string fileLogin {
            get {
                return ResourceManager.GetString("fileLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a pc.json.
        /// </summary>
        public static string filePC {
            get {
                return ResourceManager.GetString("filePC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a bios-checksum.txt.
        /// </summary>
        public static string fileShaBios {
            get {
                return ResourceManager.GetString("fileShaBios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a config-checksum.txt.
        /// </summary>
        public static string fileShaConfig {
            get {
                return ResourceManager.GetString("fileShaConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a login-checksum.txt.
        /// </summary>
        public static string fileShaLogin {
            get {
                return ResourceManager.GetString("fileShaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a pc-checksum.txt.
        /// </summary>
        public static string fileShaPC {
            get {
                return ResourceManager.GetString("fileShaPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FOP.
        /// </summary>
        public static string FOP {
            get {
                return ResourceManager.GetString("FOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Software\\FOP.
        /// </summary>
        public static string FopRegKey {
            get {
                return ResourceManager.GetString("FopRegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce.
        /// </summary>
        public static string FopRunOnceKey {
            get {
                return ResourceManager.GetString("FopRunOnceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\\Program Files\\FOP\\Rever tutorial de uso do computador.lnk.
        /// </summary>
        public static string FOPx64 {
            get {
                return ResourceManager.GetString("FOPx64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\\Program Files (x86)\\FOP\\Rever tutorial de uso do computador.lnk.
        /// </summary>
        public static string FOPx86 {
            get {
                return ResourceManager.GetString("FOPx86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a receiveFormattingData.
        /// </summary>
        public static string formatURL {
            get {
                return ResourceManager.GetString("formatURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MHz.
        /// </summary>
        public static string frequency {
            get {
                return ResourceManager.GetString("frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GB.
        /// </summary>
        public static string gb {
            get {
                return ResourceManager.GetString("gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HDD.
        /// </summary>
        public static string hdd {
            get {
                return ResourceManager.GetString("hdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 768.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PC-.
        /// </summary>
        public static string HOSTNAME_PATTERN {
            get {
                return ResourceManager.GetString("HOSTNAME_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Software\HardwareInformation.
        /// </summary>
        public static string HWINFO_REG_PATH {
            get {
                return ResourceManager.GetString("HWINFO_REG_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_about_dark.png.
        /// </summary>
        public static string icon_about_dark_path {
            get {
                return ResourceManager.GetString("icon_about_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_about_light.png.
        /// </summary>
        public static string icon_about_light_path {
            get {
                return ResourceManager.GetString("icon_about_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ahci_dark.png.
        /// </summary>
        public static string icon_ahci_dark_path {
            get {
                return ResourceManager.GetString("icon_ahci_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ahci_light.png.
        /// </summary>
        public static string icon_ahci_light_path {
            get {
                return ResourceManager.GetString("icon_ahci_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_autotheme_dark.png.
        /// </summary>
        public static string icon_autotheme_dark_path {
            get {
                return ResourceManager.GetString("icon_autotheme_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_autotheme_light.png.
        /// </summary>
        public static string icon_autotheme_light_path {
            get {
                return ResourceManager.GetString("icon_autotheme_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_bios_dark.png.
        /// </summary>
        public static string icon_bios_dark_path {
            get {
                return ResourceManager.GetString("icon_bios_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_bios_light.png.
        /// </summary>
        public static string icon_bios_light_path {
            get {
                return ResourceManager.GetString("icon_bios_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_bios_version_dark.png.
        /// </summary>
        public static string icon_bios_version_dark_path {
            get {
                return ResourceManager.GetString("icon_bios_version_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_bios_version_light.png.
        /// </summary>
        public static string icon_bios_version_light_path {
            get {
                return ResourceManager.GetString("icon_bios_version_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_brand_dark.png.
        /// </summary>
        public static string icon_brand_dark_path {
            get {
                return ResourceManager.GetString("icon_brand_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_brand_light.png.
        /// </summary>
        public static string icon_brand_light_path {
            get {
                return ResourceManager.GetString("icon_brand_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_building_dark.png.
        /// </summary>
        public static string icon_building_dark_path {
            get {
                return ResourceManager.GetString("icon_building_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_building_light.png.
        /// </summary>
        public static string icon_building_light_path {
            get {
                return ResourceManager.GetString("icon_building_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_cmos_battery_dark.png.
        /// </summary>
        public static string icon_cmos_battery_dark_path {
            get {
                return ResourceManager.GetString("icon_cmos_battery_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_cmos_battery_light.png.
        /// </summary>
        public static string icon_cmos_battery_light_path {
            get {
                return ResourceManager.GetString("icon_cmos_battery_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_cpu_dark.png.
        /// </summary>
        public static string icon_cpu_dark_path {
            get {
                return ResourceManager.GetString("icon_cpu_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_cpu_light.png.
        /// </summary>
        public static string icon_cpu_light_path {
            get {
                return ResourceManager.GetString("icon_cpu_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_darktheme_dark.png.
        /// </summary>
        public static string icon_darktheme_dark_path {
            get {
                return ResourceManager.GetString("icon_darktheme_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_darktheme_light.png.
        /// </summary>
        public static string icon_darktheme_light_path {
            get {
                return ResourceManager.GetString("icon_darktheme_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_disk_size_dark.png.
        /// </summary>
        public static string icon_disk_size_dark_path {
            get {
                return ResourceManager.GetString("icon_disk_size_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_disk_size_light.png.
        /// </summary>
        public static string icon_disk_size_light_path {
            get {
                return ResourceManager.GetString("icon_disk_size_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_gpu_dark.png.
        /// </summary>
        public static string icon_gpu_dark_path {
            get {
                return ResourceManager.GetString("icon_gpu_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_gpu_light.png.
        /// </summary>
        public static string icon_gpu_light_path {
            get {
                return ResourceManager.GetString("icon_gpu_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_hdd_dark.png.
        /// </summary>
        public static string icon_hdd_dark_path {
            get {
                return ResourceManager.GetString("icon_hdd_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_hdd_light.png.
        /// </summary>
        public static string icon_hdd_light_path {
            get {
                return ResourceManager.GetString("icon_hdd_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_hostname_dark.png.
        /// </summary>
        public static string icon_hostname_dark_path {
            get {
                return ResourceManager.GetString("icon_hostname_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_hostname_light.png.
        /// </summary>
        public static string icon_hostname_light_path {
            get {
                return ResourceManager.GetString("icon_hostname_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_in_use_dark.png.
        /// </summary>
        public static string icon_in_use_dark_path {
            get {
                return ResourceManager.GetString("icon_in_use_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_in_use_light.png.
        /// </summary>
        public static string icon_in_use_light_path {
            get {
                return ResourceManager.GetString("icon_in_use_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ip_dark.png.
        /// </summary>
        public static string icon_ip_dark_path {
            get {
                return ResourceManager.GetString("icon_ip_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ip_light.png.
        /// </summary>
        public static string icon_ip_light_path {
            get {
                return ResourceManager.GetString("icon_ip_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_letter_dark.png.
        /// </summary>
        public static string icon_letter_dark_path {
            get {
                return ResourceManager.GetString("icon_letter_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_letter_light.png.
        /// </summary>
        public static string icon_letter_light_path {
            get {
                return ResourceManager.GetString("icon_letter_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_lighttheme_dark.png.
        /// </summary>
        public static string icon_lighttheme_dark_path {
            get {
                return ResourceManager.GetString("icon_lighttheme_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_lighttheme_light.png.
        /// </summary>
        public static string icon_lighttheme_light_path {
            get {
                return ResourceManager.GetString("icon_lighttheme_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_log_dark.png.
        /// </summary>
        public static string icon_log_dark_path {
            get {
                return ResourceManager.GetString("icon_log_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_log_light.png.
        /// </summary>
        public static string icon_log_light_path {
            get {
                return ResourceManager.GetString("icon_log_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_mac_dark.png.
        /// </summary>
        public static string icon_mac_dark_path {
            get {
                return ResourceManager.GetString("icon_mac_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_mac_light.png.
        /// </summary>
        public static string icon_mac_light_path {
            get {
                return ResourceManager.GetString("icon_mac_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_model_dark.png.
        /// </summary>
        public static string icon_model_dark_path {
            get {
                return ResourceManager.GetString("icon_model_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_model_light.png.
        /// </summary>
        public static string icon_model_light_path {
            get {
                return ResourceManager.GetString("icon_model_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_password_dark.png.
        /// </summary>
        public static string icon_password_dark_path {
            get {
                return ResourceManager.GetString("icon_password_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_password_light.png.
        /// </summary>
        public static string icon_password_light_path {
            get {
                return ResourceManager.GetString("icon_password_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_patr_dark.png.
        /// </summary>
        public static string icon_patr_dark_path {
            get {
                return ResourceManager.GetString("icon_patr_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_patr_light.png.
        /// </summary>
        public static string icon_patr_light_path {
            get {
                return ResourceManager.GetString("icon_patr_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_port_dark.png.
        /// </summary>
        public static string icon_port_dark_path {
            get {
                return ResourceManager.GetString("icon_port_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_port_light.png.
        /// </summary>
        public static string icon_port_light_path {
            get {
                return ResourceManager.GetString("icon_port_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ram_dark.png.
        /// </summary>
        public static string icon_ram_dark_path {
            get {
                return ResourceManager.GetString("icon_ram_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ram_light.png.
        /// </summary>
        public static string icon_ram_light_path {
            get {
                return ResourceManager.GetString("icon_ram_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_room_dark.png.
        /// </summary>
        public static string icon_room_dark_path {
            get {
                return ResourceManager.GetString("icon_room_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_room_light.png.
        /// </summary>
        public static string icon_room_light_path {
            get {
                return ResourceManager.GetString("icon_room_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_seal_dark.png.
        /// </summary>
        public static string icon_seal_dark_path {
            get {
                return ResourceManager.GetString("icon_seal_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_seal_light.png.
        /// </summary>
        public static string icon_seal_light_path {
            get {
                return ResourceManager.GetString("icon_seal_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_secure_boot_dark.png.
        /// </summary>
        public static string icon_secure_boot_dark_path {
            get {
                return ResourceManager.GetString("icon_secure_boot_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_secure_boot_light.png.
        /// </summary>
        public static string icon_secure_boot_light_path {
            get {
                return ResourceManager.GetString("icon_secure_boot_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_serial_no_dark.png.
        /// </summary>
        public static string icon_serial_no_dark_path {
            get {
                return ResourceManager.GetString("icon_serial_no_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_serial_no_light.png.
        /// </summary>
        public static string icon_serial_no_light_path {
            get {
                return ResourceManager.GetString("icon_serial_no_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_server_dark.png.
        /// </summary>
        public static string icon_server_dark_path {
            get {
                return ResourceManager.GetString("icon_server_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_server_light.png.
        /// </summary>
        public static string icon_server_light_path {
            get {
                return ResourceManager.GetString("icon_server_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_service_dark.png.
        /// </summary>
        public static string icon_service_dark_path {
            get {
                return ResourceManager.GetString("icon_service_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_service_light.png.
        /// </summary>
        public static string icon_service_light_path {
            get {
                return ResourceManager.GetString("icon_service_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_smart_dark.png.
        /// </summary>
        public static string icon_smart_dark_path {
            get {
                return ResourceManager.GetString("icon_smart_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_smart_light.png.
        /// </summary>
        public static string icon_smart_light_path {
            get {
                return ResourceManager.GetString("icon_smart_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_standard_dark.png.
        /// </summary>
        public static string icon_standard_dark_path {
            get {
                return ResourceManager.GetString("icon_standard_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_standard_light.png.
        /// </summary>
        public static string icon_standard_light_path {
            get {
                return ResourceManager.GetString("icon_standard_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_sticker_dark.png.
        /// </summary>
        public static string icon_sticker_dark_path {
            get {
                return ResourceManager.GetString("icon_sticker_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_sticker_light.png.
        /// </summary>
        public static string icon_sticker_light_path {
            get {
                return ResourceManager.GetString("icon_sticker_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ticket_dark.png.
        /// </summary>
        public static string icon_ticket_dark_path {
            get {
                return ResourceManager.GetString("icon_ticket_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_ticket_light.png.
        /// </summary>
        public static string icon_ticket_light_path {
            get {
                return ResourceManager.GetString("icon_ticket_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_tpm_dark.png.
        /// </summary>
        public static string icon_tpm_dark_path {
            get {
                return ResourceManager.GetString("icon_tpm_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_tpm_light.png.
        /// </summary>
        public static string icon_tpm_light_path {
            get {
                return ResourceManager.GetString("icon_tpm_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_type_dark.png.
        /// </summary>
        public static string icon_type_dark_path {
            get {
                return ResourceManager.GetString("icon_type_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_type_light.png.
        /// </summary>
        public static string icon_type_light_path {
            get {
                return ResourceManager.GetString("icon_type_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_user_dark.png.
        /// </summary>
        public static string icon_user_dark_path {
            get {
                return ResourceManager.GetString("icon_user_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_user_light.png.
        /// </summary>
        public static string icon_user_light_path {
            get {
                return ResourceManager.GetString("icon_user_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_VT_x_dark.png.
        /// </summary>
        public static string icon_VT_x_dark_path {
            get {
                return ResourceManager.GetString("icon_VT_x_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_VT_x_light.png.
        /// </summary>
        public static string icon_VT_x_light_path {
            get {
                return ResourceManager.GetString("icon_VT_x_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_who_dark.png.
        /// </summary>
        public static string icon_who_dark_path {
            get {
                return ResourceManager.GetString("icon_who_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_who_light.png.
        /// </summary>
        public static string icon_who_light_path {
            get {
                return ResourceManager.GetString("icon_who_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_windows_dark.png.
        /// </summary>
        public static string icon_windows_dark_path {
            get {
                return ResourceManager.GetString("icon_windows_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\icons\\icon_windows_light.png.
        /// </summary>
        public static string icon_windows_light_path {
            get {
                return ResourceManager.GetString("icon_windows_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IDE/RAID.
        /// </summary>
        public static string ide {
            get {
                return ResourceManager.GetString("ide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .png.
        /// </summary>
        public static string imgExt {
            get {
                return ResourceManager.GetString("imgExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Definitions.
        /// </summary>
        public static string INI_SECTION_1 {
            get {
                return ResourceManager.GetString("INI_SECTION_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ServerIP.
        /// </summary>
        public static string INI_SECTION_1_11 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ServerPort.
        /// </summary>
        public static string INI_SECTION_1_12 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Buildings.
        /// </summary>
        public static string INI_SECTION_1_13 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HWTypes.
        /// </summary>
        public static string INI_SECTION_1_14 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ThemeUI.
        /// </summary>
        public static string INI_SECTION_1_15 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logo1URL.
        /// </summary>
        public static string INI_SECTION_1_16 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logo2URL.
        /// </summary>
        public static string INI_SECTION_1_17 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logo3URL.
        /// </summary>
        public static string INI_SECTION_1_18 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LogLocation.
        /// </summary>
        public static string INI_SECTION_1_9 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OrgData.
        /// </summary>
        public static string INI_SECTION_2 {
            get {
                return ResourceManager.GetString("INI_SECTION_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OrganizationFullName.
        /// </summary>
        public static string INI_SECTION_2_1 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OrganizationAcronym.
        /// </summary>
        public static string INI_SECTION_2_2 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DepartamentFullName.
        /// </summary>
        public static string INI_SECTION_2_3 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DepartamentAcronym.
        /// </summary>
        public static string INI_SECTION_2_4 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SubDepartamentFullName.
        /// </summary>
        public static string INI_SECTION_2_5 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SubDepartamentAcronym.
        /// </summary>
        public static string INI_SECTION_2_6 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a output/.
        /// </summary>
        public static string jsonServerPath {
            get {
                return ResourceManager.GetString("jsonServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LastInstallation.
        /// </summary>
        public static string lastInstall {
            get {
                return ResourceManager.GetString("lastInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LastMaintenance.
        /// </summary>
        public static string lastMaintenance {
            get {
                return ResourceManager.GetString("lastMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limited.
        /// </summary>
        public static string limitedUserType {
            get {
                return ResourceManager.GetString("limitedUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 2.
        /// </summary>
        public static string LOG_ERROR {
            get {
                return ResourceManager.GetString("LOG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .log.
        /// </summary>
        public static string LOG_FILE_EXT {
            get {
                return ResourceManager.GetString("LOG_FILE_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IT-Asset-Registration.
        /// </summary>
        public static string LOG_FILENAME_CP {
            get {
                return ResourceManager.GetString("LOG_FILENAME_CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FOP.
        /// </summary>
        public static string LOG_FILENAME_FOP {
            get {
                return ResourceManager.GetString("LOG_FILENAME_FOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0.
        /// </summary>
        public static string LOG_INFO {
            get {
                return ResourceManager.GetString("LOG_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 3.
        /// </summary>
        public static string LOG_MISC {
            get {
                return ResourceManager.GetString("LOG_MISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a XXXXXXXXXXXXXXX.
        /// </summary>
        public static string LOG_PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("LOG_PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ____________________________________________________________________________________________________.
        /// </summary>
        public static string LOG_SEPARATOR {
            get {
                return ResourceManager.GetString("LOG_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ------------------------------------------------.
        /// </summary>
        public static string LOG_SEPARATOR_SMALL {
            get {
                return ResourceManager.GetString("LOG_SEPARATOR_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HH:mm:ss.ffffff.
        /// </summary>
        public static string LOG_TIMESTAMP {
            get {
                return ResourceManager.GetString("LOG_TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1.
        /// </summary>
        public static string LOG_WARNING {
            get {
                return ResourceManager.GetString("LOG_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\header\\login_banner_dark.png.
        /// </summary>
        public static string login_banner_dark_path {
            get {
                return ResourceManager.GetString("login_banner_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\header\\login_banner_light.png.
        /// </summary>
        public static string login_banner_light_path {
            get {
                return ResourceManager.GetString("login_banner_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a System.IO.Path.GetTempPath() + Resources.fileLogin.
        /// </summary>
        public static string loginPath {
            get {
                return ResourceManager.GetString("loginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\header\\main_banner_dark.png.
        /// </summary>
        public static string main_banner_dark_path {
            get {
                return ResourceManager.GetString("main_banner_dark_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resources\\header\\main_banner_light.png.
        /// </summary>
        public static string main_banner_light_path {
            get {
                return ResourceManager.GetString("main_banner_light_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a receiveMaintenanceData.
        /// </summary>
        public static string maintenanceURL {
            get {
                return ResourceManager.GetString("maintenanceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 100.
        /// </summary>
        public static string MAX_SIZE {
            get {
                return ResourceManager.GetString("MAX_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MB.
        /// </summary>
        public static string mb {
            get {
                return ResourceManager.GetString("mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 210.
        /// </summary>
        public static string nonSecBootGPU1 {
            get {
                return ResourceManager.GetString("nonSecBootGPU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 430.
        /// </summary>
        public static string nonSecBootGPU2 {
            get {
                return ResourceManager.GetString("nonSecBootGPU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NVMe.
        /// </summary>
        public static string nvme {
            get {
                return ResourceManager.GetString("nvme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a System.IO.Path.GetTempPath() + Resources.filePC.
        /// </summary>
        public static string pcPath {
            get {
                return ResourceManager.GetString("pcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pred Fail.
        /// </summary>
        public static string predFail {
            get {
                return ResourceManager.GetString("predFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AppLog.
        /// </summary>
        public static string PROGRAMDATA_FOLDERNAME {
            get {
                return ResourceManager.GetString("PROGRAMDATA_FOLDERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAID.
        /// </summary>
        public static string raid {
            get {
                return ResourceManager.GetString("raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 2.
        /// </summary>
        public static string RETURN_ERROR {
            get {
                return ResourceManager.GetString("RETURN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0.
        /// </summary>
        public static string RETURN_SUCCESS {
            get {
                return ResourceManager.GetString("RETURN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1.
        /// </summary>
        public static string RETURN_WARNING {
            get {
                return ResourceManager.GetString("RETURN_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8.
        /// </summary>
        public static string rotatingCircleInnerCircleRadius100 {
            get {
                return ResourceManager.GetString("rotatingCircleInnerCircleRadius100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 10.
        /// </summary>
        public static string rotatingCircleInnerCircleRadius125 {
            get {
                return ResourceManager.GetString("rotatingCircleInnerCircleRadius125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 11.
        /// </summary>
        public static string rotatingCircleInnerCircleRadius150 {
            get {
                return ResourceManager.GetString("rotatingCircleInnerCircleRadius150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 14.
        /// </summary>
        public static string rotatingCircleInnerCircleRadius175 {
            get {
                return ResourceManager.GetString("rotatingCircleInnerCircleRadius175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 15.
        /// </summary>
        public static string rotatingCircleInnerCircleRadius200 {
            get {
                return ResourceManager.GetString("rotatingCircleInnerCircleRadius200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 17.
        /// </summary>
        public static string rotatingCircleInnerCircleRadius225 {
            get {
                return ResourceManager.GetString("rotatingCircleInnerCircleRadius225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 17.
        /// </summary>
        public static string rotatingCircleInnerCircleRadius250 {
            get {
                return ResourceManager.GetString("rotatingCircleInnerCircleRadius250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 22.
        /// </summary>
        public static string rotatingCircleInnerCircleRadius300 {
            get {
                return ResourceManager.GetString("rotatingCircleInnerCircleRadius300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 24.
        /// </summary>
        public static string rotatingCircleInnerCircleRadius350 {
            get {
                return ResourceManager.GetString("rotatingCircleInnerCircleRadius350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 28.
        /// </summary>
        public static string rotatingCircleNumberSpoke100 {
            get {
                return ResourceManager.GetString("rotatingCircleNumberSpoke100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 32.
        /// </summary>
        public static string rotatingCircleNumberSpoke125 {
            get {
                return ResourceManager.GetString("rotatingCircleNumberSpoke125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 36.
        /// </summary>
        public static string rotatingCircleNumberSpoke150 {
            get {
                return ResourceManager.GetString("rotatingCircleNumberSpoke150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 40.
        /// </summary>
        public static string rotatingCircleNumberSpoke175 {
            get {
                return ResourceManager.GetString("rotatingCircleNumberSpoke175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 44.
        /// </summary>
        public static string rotatingCircleNumberSpoke200 {
            get {
                return ResourceManager.GetString("rotatingCircleNumberSpoke200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 48.
        /// </summary>
        public static string rotatingCircleNumberSpoke225 {
            get {
                return ResourceManager.GetString("rotatingCircleNumberSpoke225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 52.
        /// </summary>
        public static string rotatingCircleNumberSpoke250 {
            get {
                return ResourceManager.GetString("rotatingCircleNumberSpoke250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 56.
        /// </summary>
        public static string rotatingCircleNumberSpoke300 {
            get {
                return ResourceManager.GetString("rotatingCircleNumberSpoke300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 60.
        /// </summary>
        public static string rotatingCircleNumberSpoke350 {
            get {
                return ResourceManager.GetString("rotatingCircleNumberSpoke350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 9.
        /// </summary>
        public static string rotatingCircleOuterCircleRadius100 {
            get {
                return ResourceManager.GetString("rotatingCircleOuterCircleRadius100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 12.
        /// </summary>
        public static string rotatingCircleOuterCircleRadius125 {
            get {
                return ResourceManager.GetString("rotatingCircleOuterCircleRadius125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 15.
        /// </summary>
        public static string rotatingCircleOuterCircleRadius150 {
            get {
                return ResourceManager.GetString("rotatingCircleOuterCircleRadius150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 18.
        /// </summary>
        public static string rotatingCircleOuterCircleRadius175 {
            get {
                return ResourceManager.GetString("rotatingCircleOuterCircleRadius175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 22.
        /// </summary>
        public static string rotatingCircleOuterCircleRadius200 {
            get {
                return ResourceManager.GetString("rotatingCircleOuterCircleRadius200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 24.
        /// </summary>
        public static string rotatingCircleOuterCircleRadius225 {
            get {
                return ResourceManager.GetString("rotatingCircleOuterCircleRadius225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 24.
        /// </summary>
        public static string rotatingCircleOuterCircleRadius250 {
            get {
                return ResourceManager.GetString("rotatingCircleOuterCircleRadius250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 32.
        /// </summary>
        public static string rotatingCircleOuterCircleRadius300 {
            get {
                return ResourceManager.GetString("rotatingCircleOuterCircleRadius300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 35.
        /// </summary>
        public static string rotatingCircleOuterCircleRadius350 {
            get {
                return ResourceManager.GetString("rotatingCircleOuterCircleRadius350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1.
        /// </summary>
        public static string rotatingCircleRotationSpeed {
            get {
                return ResourceManager.GetString("rotatingCircleRotationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 4.
        /// </summary>
        public static string rotatingCircleSpokeThickness100 {
            get {
                return ResourceManager.GetString("rotatingCircleSpokeThickness100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string rotatingCircleSpokeThickness125 {
            get {
                return ResourceManager.GetString("rotatingCircleSpokeThickness125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string rotatingCircleSpokeThickness150 {
            get {
                return ResourceManager.GetString("rotatingCircleSpokeThickness150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string rotatingCircleSpokeThickness175 {
            get {
                return ResourceManager.GetString("rotatingCircleSpokeThickness175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string rotatingCircleSpokeThickness200 {
            get {
                return ResourceManager.GetString("rotatingCircleSpokeThickness200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string rotatingCircleSpokeThickness225 {
            get {
                return ResourceManager.GetString("rotatingCircleSpokeThickness225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string rotatingCircleSpokeThickness250 {
            get {
                return ResourceManager.GetString("rotatingCircleSpokeThickness250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string rotatingCircleSpokeThickness300 {
            get {
                return ResourceManager.GetString("rotatingCircleSpokeThickness300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5.
        /// </summary>
        public static string rotatingCircleSpokeThickness350 {
            get {
                return ResourceManager.GetString("rotatingCircleSpokeThickness350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a same.
        /// </summary>
        public static string sameWord {
            get {
                return ResourceManager.GetString("sameWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SATA.
        /// </summary>
        public static string sata {
            get {
                return ResourceManager.GetString("sata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SSD.
        /// </summary>
        public static string ssd {
            get {
                return ResourceManager.GetString("ssd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a forneceDadosBIOS.php.
        /// </summary>
        public static string supplyBiosData {
            get {
                return ResourceManager.GetString("supplyBiosData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /etc/config.json.
        /// </summary>
        public static string supplyConfigData {
            get {
                return ResourceManager.GetString("supplyConfigData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a forneceDadosUsuario.php.
        /// </summary>
        public static string supplyLoginData {
            get {
                return ResourceManager.GetString("supplyLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a forneceDadosPC.php.
        /// </summary>
        public static string supplyPCData {
            get {
                return ResourceManager.GetString("supplyPCData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SYSTEM ROM.
        /// </summary>
        public static string systemRom {
            get {
                return ResourceManager.GetString("systemRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TB.
        /// </summary>
        public static string tb {
            get {
                return ResourceManager.GetString("tb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AppsUseLightTheme.
        /// </summary>
        public static string THEME_REG_KEY {
            get {
                return ResourceManager.GetString("THEME_REG_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize.
        /// </summary>
        public static string THEME_REG_PATH {
            get {
                return ResourceManager.GetString("THEME_REG_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1000.
        /// </summary>
        public static string TIMER_INTERVAL {
            get {
                return ResourceManager.GetString("TIMER_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To Be Filled By O.E.M..
        /// </summary>
        public static string ToBeFilledByOEM {
            get {
                return ResourceManager.GetString("ToBeFilledByOEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a today.
        /// </summary>
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UEFI.
        /// </summary>
        public static string uefi {
            get {
                return ResourceManager.GetString("uefi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SOFTWARE\\WOW6432Node\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}.
        /// </summary>
        public static string WEBVIEW2_REG_PATH_X64 {
            get {
                return ResourceManager.GetString("WEBVIEW2_REG_PATH_X64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SOFTWARE\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}.
        /// </summary>
        public static string WEBVIEW2_REG_PATH_X86 {
            get {
                return ResourceManager.GetString("WEBVIEW2_REG_PATH_X86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\.
        /// </summary>
        public static string WEBVIEW2_SYSTEM_PATH_X64 {
            get {
                return ResourceManager.GetString("WEBVIEW2_SYSTEM_PATH_X64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\\Program Files\\Microsoft\\EdgeWebView\\Application\\.
        /// </summary>
        public static string WEBVIEW2_SYSTEM_PATH_X86 {
            get {
                return ResourceManager.GetString("WEBVIEW2_SYSTEM_PATH_X86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a webview2installer.exe.
        /// </summary>
        public static string webview2file {
            get {
                return ResourceManager.GetString("webview2file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a System.IO.Path.GetTempPath() + Resources.webview2file.
        /// </summary>
        public static string webview2filePath {
            get {
                return ResourceManager.GetString("webview2filePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://go.microsoft.com/fwlink/p/?LinkId=2124703.
        /// </summary>
        public static string webview2url {
            get {
                return ResourceManager.GetString("webview2url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1366.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a \\img-windows10\\.
        /// </summary>
        public static string win10imgDir {
            get {
                return ResourceManager.GetString("win10imgDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 19041.
        /// </summary>
        public static string win10ntBuild {
            get {
                return ResourceManager.GetString("win10ntBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 10.0.19041.
        /// </summary>
        public static string win10ntFullVersion {
            get {
                return ResourceManager.GetString("win10ntFullVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 10.
        /// </summary>
        public static string win10ntMajor {
            get {
                return ResourceManager.GetString("win10ntMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0.
        /// </summary>
        public static string win10ntMinor {
            get {
                return ResourceManager.GetString("win10ntMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a \\img-windows11\\.
        /// </summary>
        public static string win11imgDir {
            get {
                return ResourceManager.GetString("win11imgDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 22000.
        /// </summary>
        public static string win11ntBuild {
            get {
                return ResourceManager.GetString("win11ntBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 10.0.22000.
        /// </summary>
        public static string win11ntFullVersion {
            get {
                return ResourceManager.GetString("win11ntFullVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 10.
        /// </summary>
        public static string win11ntMajor {
            get {
                return ResourceManager.GetString("win11ntMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0.
        /// </summary>
        public static string win11ntMinor {
            get {
                return ResourceManager.GetString("win11ntMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a \\img-windows7\\.
        /// </summary>
        public static string win7imgDir {
            get {
                return ResourceManager.GetString("win7imgDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7601.
        /// </summary>
        public static string win7ntBuild {
            get {
                return ResourceManager.GetString("win7ntBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6.1.7601.
        /// </summary>
        public static string win7ntFullVersion {
            get {
                return ResourceManager.GetString("win7ntFullVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6.
        /// </summary>
        public static string win7ntMajor {
            get {
                return ResourceManager.GetString("win7ntMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1.
        /// </summary>
        public static string win7ntMinor {
            get {
                return ResourceManager.GetString("win7ntMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 10.
        /// </summary>
        public static string windows10 {
            get {
                return ResourceManager.GetString("windows10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 11.
        /// </summary>
        public static string windows11 {
            get {
                return ResourceManager.GetString("windows11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7.
        /// </summary>
        public static string windows7 {
            get {
                return ResourceManager.GetString("windows7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8.
        /// </summary>
        public static string windows8 {
            get {
                return ResourceManager.GetString("windows8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8.1.
        /// </summary>
        public static string windows8_1 {
            get {
                return ResourceManager.GetString("windows8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
