//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstantsDLL.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConstantsDLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string AAAString1 {
            get {
                return ResourceManager.GetString("AAAString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AHCI.
        /// </summary>
        public static string ahci {
            get {
                return ResourceManager.GetString("ahci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 32.
        /// </summary>
        public static string arch32 {
            get {
                return ResourceManager.GetString("arch32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 64.
        /// </summary>
        public static string arch64 {
            get {
                return ResourceManager.GetString("arch64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BIOS.
        /// </summary>
        public static string bios {
            get {
                return ResourceManager.GetString("bios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a build.
        /// </summary>
        public static string build {
            get {
                return ResourceManager.GetString("build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -.
        /// </summary>
        public static string DASH {
            get {
                return ResourceManager.GetString("DASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DDR2.
        /// </summary>
        public static string ddr2 {
            get {
                return ResourceManager.GetString("ddr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DDR3.
        /// </summary>
        public static string ddr3 {
            get {
                return ResourceManager.GetString("ddr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 24.
        /// </summary>
        public static string ddr3memorytype {
            get {
                return ResourceManager.GetString("ddr3memorytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 24.
        /// </summary>
        public static string ddr3smbios {
            get {
                return ResourceManager.GetString("ddr3smbios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DDR4.
        /// </summary>
        public static string ddr4 {
            get {
                return ResourceManager.GetString("ddr4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 26.
        /// </summary>
        public static string ddr4smbios {
            get {
                return ResourceManager.GetString("ddr4smbios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a definitions.ini.
        /// </summary>
        public static string defFile {
            get {
                return ResourceManager.GetString("defFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a bios.json.
        /// </summary>
        public static string fileBios {
            get {
                return ResourceManager.GetString("fileBios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a config.json.
        /// </summary>
        public static string fileConfig {
            get {
                return ResourceManager.GetString("fileConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /etc/.
        /// </summary>
        public static string fileConfigPath {
            get {
                return ResourceManager.GetString("fileConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a login.json.
        /// </summary>
        public static string fileLogin {
            get {
                return ResourceManager.GetString("fileLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a pc.json.
        /// </summary>
        public static string filePC {
            get {
                return ResourceManager.GetString("filePC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a bios-checksum.txt.
        /// </summary>
        public static string fileShaBios {
            get {
                return ResourceManager.GetString("fileShaBios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a config-checksum.txt.
        /// </summary>
        public static string fileShaConfig {
            get {
                return ResourceManager.GetString("fileShaConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a login-checksum.txt.
        /// </summary>
        public static string fileShaLogin {
            get {
                return ResourceManager.GetString("fileShaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a pc-checksum.txt.
        /// </summary>
        public static string fileShaPC {
            get {
                return ResourceManager.GetString("fileShaPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a recebeDadosFormatacao.
        /// </summary>
        public static string formatURL {
            get {
                return ResourceManager.GetString("formatURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MHz.
        /// </summary>
        public static string frequency {
            get {
                return ResourceManager.GetString("frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GB.
        /// </summary>
        public static string gb {
            get {
                return ResourceManager.GetString("gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HDD.
        /// </summary>
        public static string hdd {
            get {
                return ResourceManager.GetString("hdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Software\HardwareInformation.
        /// </summary>
        public static string HWINFO_REG_PATH {
            get {
                return ResourceManager.GetString("HWINFO_REG_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IDE/RAID.
        /// </summary>
        public static string ide {
            get {
                return ResourceManager.GetString("ide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Definitions.
        /// </summary>
        public static string INI_SECTION_1 {
            get {
                return ResourceManager.GetString("INI_SECTION_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ServerIP.
        /// </summary>
        public static string INI_SECTION_1_11 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ServerPort.
        /// </summary>
        public static string INI_SECTION_1_12 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Buildings.
        /// </summary>
        public static string INI_SECTION_1_13 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HWTypes.
        /// </summary>
        public static string INI_SECTION_1_14 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ThemeUI.
        /// </summary>
        public static string INI_SECTION_1_15 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LogLocation.
        /// </summary>
        public static string INI_SECTION_1_9 {
            get {
                return ResourceManager.GetString("INI_SECTION_1_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OrgData.
        /// </summary>
        public static string INI_SECTION_2 {
            get {
                return ResourceManager.GetString("INI_SECTION_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OrganizationFullName.
        /// </summary>
        public static string INI_SECTION_2_1 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OrganizationAcronym.
        /// </summary>
        public static string INI_SECTION_2_2 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DepartamentFullName.
        /// </summary>
        public static string INI_SECTION_2_3 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DepartamentAcronym.
        /// </summary>
        public static string INI_SECTION_2_4 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SubDepartamentFullName.
        /// </summary>
        public static string INI_SECTION_2_5 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SubDepartamentAcronym.
        /// </summary>
        public static string INI_SECTION_2_6 {
            get {
                return ResourceManager.GetString("INI_SECTION_2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a output/.
        /// </summary>
        public static string jsonServerPath {
            get {
                return ResourceManager.GetString("jsonServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LastInstallation.
        /// </summary>
        public static string lastInstall {
            get {
                return ResourceManager.GetString("lastInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LastMaintenance.
        /// </summary>
        public static string lastMaintenance {
            get {
                return ResourceManager.GetString("lastMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .log.
        /// </summary>
        public static string LOG_FILE_EXT {
            get {
                return ResourceManager.GetString("LOG_FILE_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ------------------------LOG DE EXECUÇÃO------------------------.
        /// </summary>
        public static string LOG_HEADER {
            get {
                return ResourceManager.GetString("LOG_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a XXXXXXXXXXXXXXX.
        /// </summary>
        public static string LOG_PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("LOG_PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ____________________________________________________________________________________________________.
        /// </summary>
        public static string LOG_SEPARATOR {
            get {
                return ResourceManager.GetString("LOG_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ------------------------------------------------.
        /// </summary>
        public static string LOG_SEPARATOR_SMALL {
            get {
                return ResourceManager.GetString("LOG_SEPARATOR_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HH:mm:ss.ffffff.
        /// </summary>
        public static string LOG_TIMESTAMP {
            get {
                return ResourceManager.GetString("LOG_TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a recebeDadosManutencao.
        /// </summary>
        public static string maintenanceURL {
            get {
                return ResourceManager.GetString("maintenanceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MB.
        /// </summary>
        public static string mb {
            get {
                return ResourceManager.GetString("mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 210.
        /// </summary>
        public static string nonSecBootGPU1 {
            get {
                return ResourceManager.GetString("nonSecBootGPU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 430.
        /// </summary>
        public static string nonSecBootGPU2 {
            get {
                return ResourceManager.GetString("nonSecBootGPU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NVMe.
        /// </summary>
        public static string nvme {
            get {
                return ResourceManager.GetString("nvme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pred Fail.
        /// </summary>
        public static string predFail {
            get {
                return ResourceManager.GetString("predFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AppLog.
        /// </summary>
        public static string PROGRAMDATA_FOLDERNAME {
            get {
                return ResourceManager.GetString("PROGRAMDATA_FOLDERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAID.
        /// </summary>
        public static string raid {
            get {
                return ResourceManager.GetString("raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SATA.
        /// </summary>
        public static string sata {
            get {
                return ResourceManager.GetString("sata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SSD.
        /// </summary>
        public static string ssd {
            get {
                return ResourceManager.GetString("ssd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a forneceDadosBIOS.php.
        /// </summary>
        public static string supplyBiosData {
            get {
                return ResourceManager.GetString("supplyBiosData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /etc/config.json.
        /// </summary>
        public static string supplyConfigData {
            get {
                return ResourceManager.GetString("supplyConfigData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a forneceDadosPC.php.
        /// </summary>
        public static string supplyPCData {
            get {
                return ResourceManager.GetString("supplyPCData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SYSTEM ROM.
        /// </summary>
        public static string systemRom {
            get {
                return ResourceManager.GetString("systemRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TB.
        /// </summary>
        public static string tb {
            get {
                return ResourceManager.GetString("tb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AppsUseLightTheme.
        /// </summary>
        public static string THEME_REG_KEY {
            get {
                return ResourceManager.GetString("THEME_REG_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize.
        /// </summary>
        public static string THEME_REG_PATH {
            get {
                return ResourceManager.GetString("THEME_REG_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To Be Filled By O.E.M..
        /// </summary>
        public static string ToBeFilledByOEM {
            get {
                return ResourceManager.GetString("ToBeFilledByOEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UEFI.
        /// </summary>
        public static string uefi {
            get {
                return ResourceManager.GetString("uefi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SOFTWARE\\WOW6432Node\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}.
        /// </summary>
        public static string WEBVIEW2_REG_PATH_X64 {
            get {
                return ResourceManager.GetString("WEBVIEW2_REG_PATH_X64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SOFTWARE\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}.
        /// </summary>
        public static string WEBVIEW2_REG_PATH_X86 {
            get {
                return ResourceManager.GetString("WEBVIEW2_REG_PATH_X86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\.
        /// </summary>
        public static string WEBVIEW2_SYSTEM_PATH_X64 {
            get {
                return ResourceManager.GetString("WEBVIEW2_SYSTEM_PATH_X64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\\Program Files\\Microsoft\\EdgeWebView\\Application\\.
        /// </summary>
        public static string WEBVIEW2_SYSTEM_PATH_X86 {
            get {
                return ResourceManager.GetString("WEBVIEW2_SYSTEM_PATH_X86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a webview2installer.exe.
        /// </summary>
        public static string webview2file {
            get {
                return ResourceManager.GetString("webview2file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://go.microsoft.com/fwlink/p/?LinkId=2124703.
        /// </summary>
        public static string webview2url {
            get {
                return ResourceManager.GetString("webview2url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 10.
        /// </summary>
        public static string windows10 {
            get {
                return ResourceManager.GetString("windows10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 11.
        /// </summary>
        public static string windows11 {
            get {
                return ResourceManager.GetString("windows11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7.
        /// </summary>
        public static string windows7 {
            get {
                return ResourceManager.GetString("windows7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8.
        /// </summary>
        public static string windows8 {
            get {
                return ResourceManager.GetString("windows8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8.1.
        /// </summary>
        public static string windows8_1 {
            get {
                return ResourceManager.GetString("windows8_1", resourceCulture);
            }
        }
    }
}
