//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstantsDLL.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConstantsDLL.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string aaaPROJECTaaa {
            get {
                return ResourceManager.GetString("aaaPROJECTaaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Absent.
        /// </summary>
        public static string absent {
            get {
                return ResourceManager.GetString("absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enabled.
        /// </summary>
        public static string activated {
            get {
                return ResourceManager.GetString("activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There is already an instance of the program running!.
        /// </summary>
        public static string ALREADY_RUNNING {
            get {
                return ResourceManager.GetString("ALREADY_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clear delivery data and cancel run on next boot.
        /// </summary>
        public static string cancelExecution {
            get {
                return ResourceManager.GetString("cancelExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete delivery data.
        /// </summary>
        public static string cancelExecutionResError {
            get {
                return ResourceManager.GetString("cancelExecutionResError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disabled.
        /// </summary>
        public static string deactivated {
            get {
                return ResourceManager.GetString("deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Send delivery data and run on next boot.
        /// </summary>
        public static string doExecution {
            get {
                return ResourceManager.GetString("doExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Send delivery data.
        /// </summary>
        public static string doExecutionResError {
            get {
                return ResourceManager.GetString("doExecutionResError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error.
        /// </summary>
        public static string ERROR_WINDOWTITLE {
            get {
                return ResourceManager.GetString("ERROR_WINDOWTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill in the required fields!.
        /// </summary>
        public static string fillForm {
            get {
                return ResourceManager.GetString("fillForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Finishing up.
        /// </summary>
        public static string finaleScreen {
            get {
                return ResourceManager.GetString("finaleScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Finish.
        /// </summary>
        public static string finishText {
            get {
                return ResourceManager.GetString("finishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Intranet connection required..
        /// </summary>
        public static string INTRANET_REQUIRED {
            get {
                return ResourceManager.GetString("INTRANET_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Intro.
        /// </summary>
        public static string introScreen {
            get {
                return ResourceManager.GetString("introScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Press Enter to close....
        /// </summary>
        public static string KEY_FINISH {
            get {
                return ResourceManager.GetString("KEY_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formatting.
        /// </summary>
        public static string listModeGUIFormat {
            get {
                return ResourceManager.GetString("listModeGUIFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maintenance.
        /// </summary>
        public static string listModeGUIMaintenance {
            get {
                return ResourceManager.GetString("listModeGUIMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        public static string listNo0 {
            get {
                return ResourceManager.GetString("listNo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a N.
        /// </summary>
        public static string listNo1 {
            get {
                return ResourceManager.GetString("listNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a n.
        /// </summary>
        public static string listNo2 {
            get {
                return ResourceManager.GetString("listNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Employee.
        /// </summary>
        public static string listStandardGUIEmployee {
            get {
                return ResourceManager.GetString("listStandardGUIEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Student.
        /// </summary>
        public static string listStandardGUIStudent {
            get {
                return ResourceManager.GetString("listStandardGUIStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        public static string listYes0 {
            get {
                return ResourceManager.GetString("listYes0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Y.
        /// </summary>
        public static string listYes1 {
            get {
                return ResourceManager.GetString("listYes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a y.
        /// </summary>
        public static string listYes2 {
            get {
                return ResourceManager.GetString("listYes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Found dependency files.
        /// </summary>
        public static string LOG_APPFILE_FOUND {
            get {
                return ResourceManager.GetString("LOG_APPFILE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One or more missing dependency files.
        /// </summary>
        public static string LOG_APPFILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOG_APPFILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Running in DEBUG mode.
        /// </summary>
        public static string LOG_DEBUG_MODE {
            get {
                return ResourceManager.GetString("LOG_DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Definitions file found.
        /// </summary>
        public static string LOG_DEFFILE_FOUND {
            get {
                return ResourceManager.GetString("LOG_DEFFILE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Definitions file not found.
        /// </summary>
        public static string LOG_DEFFILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOG_DEFFILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;ERROR&gt;.
        /// </summary>
        public static string LOG_ERROR_ATTR {
            get {
                return ResourceManager.GetString("LOG_ERROR_ATTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ------------------------ EXECUTION LOG ------------------------.
        /// </summary>
        public static string LOG_HEADER {
            get {
                return ResourceManager.GetString("LOG_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;INFORMATION&gt;.
        /// </summary>
        public static string LOG_INFO_ATTR {
            get {
                return ResourceManager.GetString("LOG_INFO_ATTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Start of execution.
        /// </summary>
        public static string LOG_INIT {
            get {
                return ResourceManager.GetString("LOG_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authenticating user.
        /// </summary>
        public static string LOG_INIT_LOGIN {
            get {
                return ResourceManager.GetString("LOG_INIT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authentication failed.
        /// </summary>
        public static string LOG_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOG_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authentication performed successfully.
        /// </summary>
        public static string LOG_LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Running in RELEASE mode.
        /// </summary>
        public static string LOG_RELEASE_MODE {
            get {
                return ResourceManager.GetString("LOG_RELEASE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;WARNING&gt;.
        /// </summary>
        public static string LOG_WARNING_ATTR {
            get {
                return ResourceManager.GetString("LOG_WARNING_ATTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Found log file, adding information.
        /// </summary>
        public static string LOGFILE_EXISTS {
            get {
                return ResourceManager.GetString("LOGFILE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nonexistent log file, creating new file.
        /// </summary>
        public static string LOGFILE_NOTEXISTS {
            get {
                return ResourceManager.GetString("LOGFILE_NOTEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Next.
        /// </summary>
        public static string nextText {
            get {
                return ResourceManager.GetString("nextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill in your credentials..
        /// </summary>
        public static string NO_AUTH {
            get {
                return ResourceManager.GetString("NO_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Not determined.
        /// </summary>
        public static string notDetermined {
            get {
                return ResourceManager.GetString("notDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nonexistent.
        /// </summary>
        public static string notExistant {
            get {
                return ResourceManager.GetString("notExistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Not supported.
        /// </summary>
        public static string notSupported {
            get {
                return ResourceManager.GetString("notSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One or more INI file parameters are malformed.
        /// </summary>
        public static string PARAMETER_ERROR {
            get {
                return ResourceManager.GetString("PARAMETER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Asset dropped, registration cancelled. Revert drop and try again.
        /// </summary>
        public static string PC_DROPPED {
            get {
                return ResourceManager.GetString("PC_DROPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assets not initially registered by the &apos;Hardware Collection and Asset Registration&apos; software. First register and then try again..
        /// </summary>
        public static string pcNotRegistered {
            get {
                return ResourceManager.GetString("pcNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Insufficient resolution. This program only supports resolutions equal to or greater than {0}x{1}..
        /// </summary>
        public static string resolutionWarning {
            get {
                return ResourceManager.GetString("resolutionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Server not found. Please select a valid server!.
        /// </summary>
        public static string SERVER_NOT_FOUND_ERROR {
            get {
                return ResourceManager.GetString("SERVER_NOT_FOUND_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknown.
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please wait.
        /// </summary>
        public static string waitText {
            get {
                return ResourceManager.GetString("waitText", resourceCulture);
            }
        }
    }
}
