//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstantsDLL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// 
/// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// 
/// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConstantsDLL.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// 
/// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// 
/// </summary>
        public static string aaaPROJECTaaa {
            get {
                return ResourceManager.GetString("aaaPROJECTaaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// 
/// </summary>
        public static string ABSENT {
            get {
                return ResourceManager.GetString("ABSENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// 
/// </summary>
        public static string ACTIVATED {
            get {
                return ResourceManager.GetString("ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an instance of the program running!.
        /// 
/// </summary>
        public static string ALREADY_RUNNING {
            get {
                return ResourceManager.GetString("ALREADY_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset disposed, registration cancelled. Revert the dispose and try again.
        /// 
/// </summary>
        public static string ASSET_DROPPED {
            get {
                return ResourceManager.GetString("ASSET_DROPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets not initially registered by the &apos;Asset Information and Registration&apos; software. First register and then try again..
        /// 
/// </summary>
        public static string ASSET_NOT_REGISTERED {
            get {
                return ResourceManager.GetString("ASSET_NOT_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear delivery data and cancel run on next boot.
        /// 
/// </summary>
        public static string CANCEL_EXECUTION {
            get {
                return ResourceManager.GetString("CANCEL_EXECUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete delivery data.
        /// 
/// </summary>
        public static string CANCEL_EXECUTION_RES_ERROR {
            get {
                return ResourceManager.GetString("CANCEL_EXECUTION_RES_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// 
/// </summary>
        public static string DEACTIVATED {
            get {
                return ResourceManager.GetString("DEACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send delivery data and run on next boot.
        /// 
/// </summary>
        public static string DO_EXECUTION {
            get {
                return ResourceManager.GetString("DO_EXECUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send delivery data.
        /// 
/// </summary>
        public static string DO_EXECUTION_RES_ERROR {
            get {
                return ResourceManager.GetString("DO_EXECUTION_RES_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// 
/// </summary>
        public static string ERROR_WINDOWTITLE {
            get {
                return ResourceManager.GetString("ERROR_WINDOWTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the required fields!.
        /// 
/// </summary>
        public static string FILL_FORM {
            get {
                return ResourceManager.GetString("FILL_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing up.
        /// 
/// </summary>
        public static string FINALE_SCREEN {
            get {
                return ResourceManager.GetString("FINALE_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// 
/// </summary>
        public static string FINISH_TEXT {
            get {
                return ResourceManager.GetString("FINISH_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intranet connection required..
        /// 
/// </summary>
        public static string INTRANET_REQUIRED {
            get {
                return ResourceManager.GetString("INTRANET_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// 
/// </summary>
        public static string INTRO_SCREEN {
            get {
                return ResourceManager.GetString("INTRO_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to close....
        /// 
/// </summary>
        public static string KEY_FINISH {
            get {
                return ResourceManager.GetString("KEY_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// 
/// </summary>
        public static string LIST_MODE_GUI_FORMAT {
            get {
                return ResourceManager.GetString("LIST_MODE_GUI_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// 
/// </summary>
        public static string LIST_MODE_GUI_MAINTENANCE {
            get {
                return ResourceManager.GetString("LIST_MODE_GUI_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// 
/// </summary>
        public static string LIST_NO_0 {
            get {
                return ResourceManager.GetString("LIST_NO_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// 
/// </summary>
        public static string LIST_NO_1 {
            get {
                return ResourceManager.GetString("LIST_NO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// 
/// </summary>
        public static string LIST_NO_2 {
            get {
                return ResourceManager.GetString("LIST_NO_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// 
/// </summary>
        public static string LIST_STANDARD_GUI_EMPLOYEE {
            get {
                return ResourceManager.GetString("LIST_STANDARD_GUI_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// 
/// </summary>
        public static string LIST_STANDARD_GUI_STUDENT {
            get {
                return ResourceManager.GetString("LIST_STANDARD_GUI_STUDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// 
/// </summary>
        public static string LIST_YES_0 {
            get {
                return ResourceManager.GetString("LIST_YES_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// 
/// </summary>
        public static string LIST_YES_1 {
            get {
                return ResourceManager.GetString("LIST_YES_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// 
/// </summary>
        public static string LIST_YES_2 {
            get {
                return ResourceManager.GetString("LIST_YES_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found dependency files.
        /// 
/// </summary>
        public static string LOG_APPFILE_FOUND {
            get {
                return ResourceManager.GetString("LOG_APPFILE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more missing dependency files.
        /// 
/// </summary>
        public static string LOG_APPFILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOG_APPFILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// 
/// </summary>
        public static string LOG_CHECKING_FOR_UPDATES {
            get {
                return ResourceManager.GetString("LOG_CHECKING_FOR_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing updater window.
        /// 
/// </summary>
        public static string LOG_CLOSING_UPDATER {
            get {
                return ResourceManager.GetString("LOG_CLOSING_UPDATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to GitHub.
        /// 
/// </summary>
        public static string LOG_CONNECTING_GITHUB {
            get {
                return ResourceManager.GetString("LOG_CONNECTING_GITHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running in DEBUG mode.
        /// 
/// </summary>
        public static string LOG_DEBUG_MODE {
            get {
                return ResourceManager.GetString("LOG_DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions file found.
        /// 
/// </summary>
        public static string LOG_DEFFILE_FOUND {
            get {
                return ResourceManager.GetString("LOG_DEFFILE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions file not found.
        /// 
/// </summary>
        public static string LOG_DEFFILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOG_DEFFILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ERROR&gt;.
        /// 
/// </summary>
        public static string LOG_ERROR_ATTR {
            get {
                return ResourceManager.GetString("LOG_ERROR_ATTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub unreachable.
        /// 
/// </summary>
        public static string LOG_GITHUB_UNREACHABLE {
            get {
                return ResourceManager.GetString("LOG_GITHUB_UNREACHABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------ EXECUTION LOG ------------------------.
        /// 
/// </summary>
        public static string LOG_HEADER {
            get {
                return ResourceManager.GetString("LOG_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;INFORMATION&gt;.
        /// 
/// </summary>
        public static string LOG_INFO_ATTR {
            get {
                return ResourceManager.GetString("LOG_INFO_ATTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of execution.
        /// 
/// </summary>
        public static string LOG_INIT {
            get {
                return ResourceManager.GetString("LOG_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating user.
        /// 
/// </summary>
        public static string LOG_INIT_LOGIN {
            get {
                return ResourceManager.GetString("LOG_INIT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// 
/// </summary>
        public static string LOG_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOG_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication performed successfully.
        /// 
/// </summary>
        public static string LOG_LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection available.
        /// 
/// </summary>
        public static string LOG_NO_INTERNET_AVAILABLE {
            get {
                return ResourceManager.GetString("LOG_NO_INTERNET_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening About window.
        /// 
/// </summary>
        public static string LOG_OPENING_ABOUTBOX {
            get {
                return ResourceManager.GetString("LOG_OPENING_ABOUTBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing release on GitHub.
        /// 
/// </summary>
        public static string LOG_OPENING_GITHUB {
            get {
                return ResourceManager.GetString("LOG_OPENING_GITHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running in RELEASE mode.
        /// 
/// </summary>
        public static string LOG_RELEASE_MODE {
            get {
                return ResourceManager.GetString("LOG_RELEASE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check for updates.
        /// 
/// </summary>
        public static string LOG_UPDATE_CHECK_IMPOSSIBLE {
            get {
                return ResourceManager.GetString("LOG_UPDATE_CHECK_IMPOSSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;WARNING&gt;.
        /// 
/// </summary>
        public static string LOG_WARNING_ATTR {
            get {
                return ResourceManager.GetString("LOG_WARNING_ATTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found log file, adding information.
        /// 
/// </summary>
        public static string LOGFILE_EXISTS {
            get {
                return ResourceManager.GetString("LOGFILE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonexistent log file, creating new file.
        /// 
/// </summary>
        public static string LOGFILE_NOTEXISTS {
            get {
                return ResourceManager.GetString("LOGFILE_NOTEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// 
/// </summary>
        public static string NEW_VERSION_AVAILABLE {
            get {
                return ResourceManager.GetString("NEW_VERSION_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// 
/// </summary>
        public static string NEXT_TEXT {
            get {
                return ResourceManager.GetString("NEXT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in your credentials..
        /// 
/// </summary>
        public static string NO_AUTH {
            get {
                return ResourceManager.GetString("NO_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your software is up-to-date..
        /// 
/// </summary>
        public static string NO_VERSION_AVAILABLE {
            get {
                return ResourceManager.GetString("NO_VERSION_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not determined.
        /// 
/// </summary>
        public static string NOT_DETERMINED {
            get {
                return ResourceManager.GetString("NOT_DETERMINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonexistent.
        /// 
/// </summary>
        public static string NOT_EXISTANT {
            get {
                return ResourceManager.GetString("NOT_EXISTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// 
/// </summary>
        public static string NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// 
/// </summary>
        public static string OF {
            get {
                return ResourceManager.GetString("OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more INI file parameters are malformed.
        /// 
/// </summary>
        public static string PARAMETER_ERROR {
            get {
                return ResourceManager.GetString("PARAMETER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient resolution. This program only supports resolutions equal to or greater than {0}x{1}..
        /// 
/// </summary>
        public static string RESOLUTION_WARNING {
            get {
                return ResourceManager.GetString("RESOLUTION_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not found. Please select a valid server!.
        /// 
/// </summary>
        public static string SERVER_NOT_FOUND_ERROR {
            get {
                return ResourceManager.GetString("SERVER_NOT_FOUND_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// 
/// </summary>
        public static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// 
/// </summary>
        public static string WAIT_TEXT {
            get {
                return ResourceManager.GetString("WAIT_TEXT", resourceCulture);
            }
        }
    }
}
