//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstantsDLL.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConstantsDLL.Properties.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string aaaPROJECTaaa {
            get {
                return ResourceManager.GetString("aaaPROJECTaaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Absent.
        /// </summary>
        public static string ABSENT {
            get {
                return ResourceManager.GetString("ABSENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enabled.
        /// </summary>
        public static string ACTIVATED {
            get {
                return ResourceManager.GetString("ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There is already an instance of the program running!.
        /// </summary>
        public static string ALREADY_RUNNING {
            get {
                return ResourceManager.GetString("ALREADY_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Asset added.
        /// </summary>
        public static string ASSET_ADDED {
            get {
                return ResourceManager.GetString("ASSET_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Asset disposed, registration cancelled. Revert the dispose and try again.
        /// </summary>
        public static string ASSET_DROPPED {
            get {
                return ResourceManager.GetString("ASSET_DROPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Asset not added.
        /// </summary>
        public static string ASSET_NOT_ADDED {
            get {
                return ResourceManager.GetString("ASSET_NOT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assets not initially registered by the &apos;Asset Information and Registration&apos; software. First register and then try again..
        /// </summary>
        public static string ASSET_NOT_REGISTERED {
            get {
                return ResourceManager.GetString("ASSET_NOT_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Asset not updated.
        /// </summary>
        public static string ASSET_NOT_UPDATED {
            get {
                return ResourceManager.GetString("ASSET_NOT_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Asset updated.
        /// </summary>
        public static string ASSET_UPDATED {
            get {
                return ResourceManager.GetString("ASSET_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clear delivery data and cancel run on next boot.
        /// </summary>
        public static string CANCEL_EXECUTION {
            get {
                return ResourceManager.GetString("CANCEL_EXECUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete delivery data.
        /// </summary>
        public static string CANCEL_EXECUTION_RES_ERROR {
            get {
                return ResourceManager.GetString("CANCEL_EXECUTION_RES_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disabled.
        /// </summary>
        public static string DEACTIVATED {
            get {
                return ResourceManager.GetString("DEACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Send delivery data and run on next boot.
        /// </summary>
        public static string DO_EXECUTION {
            get {
                return ResourceManager.GetString("DO_EXECUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Send delivery data.
        /// </summary>
        public static string DO_EXECUTION_RES_ERROR {
            get {
                return ResourceManager.GetString("DO_EXECUTION_RES_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error.
        /// </summary>
        public static string ERROR_WINDOWTITLE {
            get {
                return ResourceManager.GetString("ERROR_WINDOWTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill in the required fields!.
        /// </summary>
        public static string FILL_FORM {
            get {
                return ResourceManager.GetString("FILL_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill in the server data.
        /// </summary>
        public static string FILL_IN_SERVER_DETAILS {
            get {
                return ResourceManager.GetString("FILL_IN_SERVER_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill in your credentials..
        /// </summary>
        public static string FILL_IN_YOUR_CREDENTIALS {
            get {
                return ResourceManager.GetString("FILL_IN_YOUR_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Finishing up.
        /// </summary>
        public static string FINALE_SCREEN {
            get {
                return ResourceManager.GetString("FINALE_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Finish.
        /// </summary>
        public static string FINISH_TEXT {
            get {
                return ResourceManager.GetString("FINISH_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Free.
        /// </summary>
        public static string FREE {
            get {
                return ResourceManager.GetString("FREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Intranet connection required..
        /// </summary>
        public static string INTRANET_REQUIRED {
            get {
                return ResourceManager.GetString("INTRANET_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Intro.
        /// </summary>
        public static string INTRO_SCREEN {
            get {
                return ResourceManager.GetString("INTRO_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid credentials. Try again..
        /// </summary>
        public static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Press Enter to close....
        /// </summary>
        public static string KEY_FINISH {
            get {
                return ResourceManager.GetString("KEY_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formatting.
        /// </summary>
        public static string LIST_MODE_GUI_FORMAT {
            get {
                return ResourceManager.GetString("LIST_MODE_GUI_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maintenance.
        /// </summary>
        public static string LIST_MODE_GUI_MAINTENANCE {
            get {
                return ResourceManager.GetString("LIST_MODE_GUI_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        public static string LIST_NO_0 {
            get {
                return ResourceManager.GetString("LIST_NO_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a N.
        /// </summary>
        public static string LIST_NO_1 {
            get {
                return ResourceManager.GetString("LIST_NO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a n.
        /// </summary>
        public static string LIST_NO_2 {
            get {
                return ResourceManager.GetString("LIST_NO_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Employee.
        /// </summary>
        public static string LIST_STANDARD_GUI_EMPLOYEE {
            get {
                return ResourceManager.GetString("LIST_STANDARD_GUI_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Student.
        /// </summary>
        public static string LIST_STANDARD_GUI_STUDENT {
            get {
                return ResourceManager.GetString("LIST_STANDARD_GUI_STUDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        public static string LIST_YES_0 {
            get {
                return ResourceManager.GetString("LIST_YES_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Y.
        /// </summary>
        public static string LIST_YES_1 {
            get {
                return ResourceManager.GetString("LIST_YES_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a y.
        /// </summary>
        public static string LIST_YES_2 {
            get {
                return ResourceManager.GetString("LIST_YES_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Found log file, adding information.
        /// </summary>
        public static string LOGFILE_EXISTS {
            get {
                return ResourceManager.GetString("LOGFILE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nonexistent log file, creating new file.
        /// </summary>
        public static string LOGFILE_NOTEXISTS {
            get {
                return ResourceManager.GetString("LOGFILE_NOTEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New version available!.
        /// </summary>
        public static string NEW_VERSION_AVAILABLE {
            get {
                return ResourceManager.GetString("NEW_VERSION_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Next.
        /// </summary>
        public static string NEXT_TEXT {
            get {
                return ResourceManager.GetString("NEXT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your software is up-to-date.
        /// </summary>
        public static string NO_NEW_VERSION_AVAILABLE {
            get {
                return ResourceManager.GetString("NO_NEW_VERSION_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No pending items found.
        /// </summary>
        public static string NO_PENDENCIES {
            get {
                return ResourceManager.GetString("NO_PENDENCIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Not determined.
        /// </summary>
        public static string NOT_DETERMINED {
            get {
                return ResourceManager.GetString("NOT_DETERMINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nonexistent.
        /// </summary>
        public static string NOT_EXISTANT {
            get {
                return ResourceManager.GetString("NOT_EXISTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Not supported.
        /// </summary>
        public static string NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a of.
        /// </summary>
        public static string OF {
            get {
                return ResourceManager.GetString("OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One or more JSON file parameters are malformed.
        /// </summary>
        public static string PARAMETER_ERROR {
            get {
                return ResourceManager.GetString("PARAMETER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a pending item(s).
        /// </summary>
        public static string PENDENCIES {
            get {
                return ResourceManager.GetString("PENDENCIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Insufficient resolution. This program only supports resolutions equal to or greater than {0}x{1}..
        /// </summary>
        public static string RESOLUTION_WARNING {
            get {
                return ResourceManager.GetString("RESOLUTION_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error in the APCS service.
        /// </summary>
        public static string SERVER_ERROR {
            get {
                return ResourceManager.GetString("SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Server not found. Please select a valid server!.
        /// </summary>
        public static string SERVER_NOT_FOUND_ERROR {
            get {
                return ResourceManager.GetString("SERVER_NOT_FOUND_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Success.
        /// </summary>
        public static string SUCCESS_WINDOWTITLE {
            get {
                return ResourceManager.GetString("SUCCESS_WINDOWTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknown.
        /// </summary>
        public static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unregistered hardware model.
        /// </summary>
        public static string UNREGISTERED_MODEL {
            get {
                return ResourceManager.GetString("UNREGISTERED_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please wait.
        /// </summary>
        public static string WAIT_TEXT {
            get {
                return ResourceManager.GetString("WAIT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Notice.
        /// </summary>
        public static string WARNING_WINDOWTITLE {
            get {
                return ResourceManager.GetString("WARNING_WINDOWTITLE", resourceCulture);
            }
        }
    }
}
